### ISSUE TITLE
Feature request: windows-sys feature should not require linking with windows.lib

### ISSUE THREAD

**Issue by korDen** [microsoft/windows-rs#1573] opened 2022-02-28 18:26 UTC
### Motivation

Since windows-sys is bare-bones ffi that has no wrappers, it should not require linking with windows.lib.

### Rationale and alternatives

While normally it wouldn't matter and the unused library symbols would get discarded at link-time, it is still unnecessary and complicates build process when using external build tools. For example, bazel is currently having issues propagating .lib dependencies across targets since only the final binary is required to link with .lib. As a result, I cannot use windows crate with bazel. I was hoping that I could at least use windows-sys crate since it has no wrappers, but that doesn't work either since windows-sys too is pulling the windows.lib.

For now, my only option is to use winapi crate which is a bit unfortunate.

**Comment by kennykerr** [comment] 2022-03-02 00:07
The `windows-sys` crate declares all the Windows API function exports that require `windows.lib` for importing those functions. 

Can you explain a bit more what exactly the problem is? We could make the target dependencies default/optional but I'd like to have a better idea why the current approach is a problem since this is the first time I have heard of this being an issue.

**Comment by kennykerr** [comment] 2022-03-07 16:41
Closing for now. Feel free to add more context here. By the way, the `winapi` crate works the same way when building with GNU: https://crates.io/crates/winapi/0.3.9/dependencies

**Closed by kennykerr** 2022-03-07 16:41 UTC
Labels: enhancement
