### ISSUE TITLE
Requesting an example of how to implement a COM interface

### ISSUE THREAD

**Issue by tecywiz121** [microsoft/windows-rs#429] opened 2021-01-22 04:50 UTC
I have a fairly simple C++ program that turns on a [blink(1)](https://blink1.thingm.com/) based on a capture device's mute state.

I'd love to port that code to Rust, if possible, but I don't know how to implement the `IMMNotificationClient` or `IAudioEndpointVolumeCallback` interfaces.

I noticed that there is the [`implement`](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/attr.implement.html) macro, but the documentation seems a bit sparse. If there is an example of how to do this, could you point me toward it, and if not, I humbly request one!

**Comment by kennykerr** [comment] 2021-01-22 05:39
The `implement` macro currently only supports WinRT interfaces, but I am working on adding support for COM interfaces like `IAudioEndpointVolumeCallback` and should be coming soon.

**Comment by peacememories** [comment] 2021-01-22 12:50
Thanks for working on this, I need to be able to implement DirectShow filters 😅

**Comment by agausmann** [comment] 2021-04-17 17:39
I'm also affected by this, in the meantime, is there some way to implement interfaces by hand?

**Comment by rylev** [comment] 2021-04-20 15:09
Implementing COM interfaces from scratch is non-trivial but very much possible. It does take quite a bit of knowledge of how COM works under the hood though. You can have a look at https://github.com/microsoft/com-rs (specifically the code gen aspects of that crate) for some clues.

**Comment by kennykerr** [comment] 2021-04-21 03:05
Duplicate of #81 - working on it.

**Closed by kennykerr** 2021-04-21 03:05 UTC
Labels: documentation, enhancement

**Comment by knopp** [comment] 2021-05-18 17:55
> I'm also affected by this, in the meantime, is there some way to implement interfaces by hand?

[Here's](https://gist.github.com/knopp/52265165b62091ccdc28a5b06d422be5) an example of implementing drag&drop com interfaces by hand. It is doable but less than ideal. A macro would be very welcome indeed :)

**Comment by kennykerr** [comment] 2021-05-18 18:01
That's all I am working on at the moment. 😉
