### ISSUE TITLE
Unclear how to use IMMDevice::GetState

### ISSUE THREAD

**Issue by HEnquist** [microsoft/windows-rs#2909] opened 2024-03-04 22:01 UTC
### Summary

The function GetState on an IMMDevice is quite confusing.

The [documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Media/Audio/trait.IMMDevice_Impl.html#tymethod.GetState) says:
```
fn GetState(&self, pdwstate: *mut u32) -> DEVICE_STATE;
```
It appears that the actual result gets written to the `pwdstate` variable, and the returned `DEVICE_STATE` is zero. Is this the intended behaviour? It would be much more logical if the function took no arguments, and returned the state in the result.

**Comment by kennykerr** [comment] 2024-03-04 22:14
I think this is a duplicate of https://github.com/microsoft/win32metadata/issues/1856 - looks like that was just fixed.

**Closed** 2024-03-05 13:48 UTC
Labels: question
