### ISSUE TITLE
Problems stemming from the `AssociatedEnum` attribute

### ISSUE THREAD

**Issue by glandium** [microsoft/windows-rs#2784] opened 2024-01-10 06:28 UTC
### Summary

In 0.48.0, CoInitializeEx was taking a COINIT. In 0.52, it takes a u32, while COINIT is i32. So using the COINIT_* constants doesn't work without a cast or a conversion, which is kind of a bummer.

**Comment by riverar** [comment] 2024-01-10 08:52
This is expected.

The enumerator values in the `tagCOINIT` enumeration are `i32` (C++ default):
```cpp
typedef enum tagCOINIT
{
  COINIT_APARTMENTTHREADED  = 0x2,      // Apartment model
  COINIT_MULTITHREADED      = COINITBASE_MULTITHREADED,
  COINIT_DISABLE_OLE1DDE    = 0x4,      // Don't use DDE for Ole1 support.
  COINIT_SPEED_OVER_MEMORY  = 0x8,      // Trade memory for speed.
} COINIT;
```

The dwCoInit parameter for the CoInitializeEx function is defined as accepting `DWORD` (`u32`) values:
```cpp
WINOLEAPI
CoInitializeEx(
  _In_opt_ LPVOID pvReserved,
  _In_ DWORD dwCoInit
);
```

Upstream metadata does annotate the enumeration relationship here but I defer to @kennykerr to comment on the challenges there.

```csharp
public unsafe static extern HRESULT CoInitializeEx(
  [Optional][In][Reserved] void* pvReserved,
  [In][AssociatedEnum("COINIT")] uint dwCoInit
);
```

**Comment by kennykerr** [comment] 2024-01-10 11:51
The issue doesn't mention the crate this question applies to. The `AssociatedEnum` attribute is used to generate more idiomatic bindings for the `windows` crate while the `windows-sys` crate sticks to the actual types to ensure that the raw bindings provided by the `windows-sys` crate faithfully and accurately reflect the ABI for the original API. 

This stems from a change in the Win32 metadata. I assume it's because there's a discrepancy between the parameter type and the enum type. The parameter type is unsigned (`DWORD`) while the enum (`COINIT`) doesn't name an underlying type and is thus assumed to be signed by the C++ compiler.

**Comment by kennykerr** [comment] 2024-01-10 15:07
As I mentioned here https://github.com/microsoft/windows-rs/issues/2782#issuecomment-1884711623, we could in theory replace these types if we can prove that they are ABI compatible.

**Comment by riverar** [comment] 2024-01-10 18:44
When you consider external code being brought in (e.g. static lib), I believe it's possible that dependent code may be optimized around a value's type where mixing unsigned and signed types could result in bugs.

**Comment by kennykerr** [comment] 2024-01-12 17:51
We should get a repro to be sure. Otherwise, this seems like a needless inconvenience.

**Comment by ChrisDenton** [comment] 2024-01-12 19:55
I can't really think of a case where being signed or not matters in FFI, Or at least not in any ABI I'm aware of. And LLVM itself doesn't even track signed vs. unsigned. It has one [integer type](https://llvm.org/docs/LangRef.html#t-integer) that just takes a bit width. Signed or unsigned is a useful fiction of the language, which will then use it to tell LLVM to use the relevant operation (e.g. `sdiv` or `udiv` ). But you can freely mix them without issue.

**Comment by kennykerr** [comment] 2024-01-15 16:17
Thanks Sam, in that case probably best to close this issue as well as #2782 as won't fix.

**Comment by glandium** [comment] 2024-01-15 20:41
The signedness doesn't matter for the accepted COINIT values, though.

**Comment by kennykerr** [comment] 2024-01-16 14:34
It may seem ridiculous, but the Windows API was designed when C was the cool new language and C didn't have a problem with this. 😏

**Comment by kennykerr** [comment] 2024-01-24 01:41
I don't think we've clearly identified the risk but neither have we ruled out any problems. There seems to be some risk in adjusting these types beyond parameter binding, which we handle today already, so I'll probably leave it there unless there is some additional data someone can provide.

**Closed** 2024-01-24 21:48 UTC
Labels: question
