### ISSUE TITLE
Implement Macro Does Not Allow Type Parameters

### ISSUE THREAD

**Issue by Nerixyz** [microsoft/windows-rs#804] opened 2021-05-13 17:48 UTC
Consider the following example (from the [test code](https://github.com/microsoft/windows-rs/blob/master/tests/implement/tests/implement.rs#L21-L38)):

```rust
#[implement(
    extend Windows::UI::Xaml::Application,
    override OnLaunched OnBackgroundActivated,
    Windows::Foundation::IStringable,
    Windows::Foundation::IClosable,
)]
struct AppWithOverrides<T> {}

#[allow(non_snake_case)]
impl <T: IntoIterator + 'static> AppWithOverrides<T> {
    fn ToString(&self) -> Result<HSTRING> {
        Ok("Stringable".into())
    }

    fn Close(&self) -> Result<()> {
        Ok(())
    }
}
```

This would be needed for implementing collections (like `IVector`).

When generating `AppWithOverrides_box`, it doesn't include the type parameters in the `struct` and `impl`.

**Comment by kennykerr** [comment] 2021-05-17 15:47
Thanks, I'm aware of this limitation. I'm planning to support generics as part of #81.

**Comment by kennykerr** [comment] 2021-05-17 17:45
I'm not yet sure whether to support generic structs or just generic instantiations or both. By generic struct I mean:

```rust
#[implement(Windows::Foundation::Collections::IVector<T>)]
struct Thing<T> {
    // ...
}
```

And by generic instantiation I mean:

```rust
#[implement(Windows::Foundation::Collections::IVector<i32>)]
struct Thing {
    // ...
}
```

I suspect we'll need both. I'm unsure whether we need generic structs that aren't used as WinRT type parameters.

**Comment by Nerixyz** [comment] 2021-05-17 18:24
I think it'd be good to support generic structs. When implementing a custom implementation for `IVector` for example, it's probably necessary.

**Comment by kennykerr** [comment] 2021-05-24 16:37
Thanks for the feedback! I'll track this as a duplicate of #81

**Closed by kennykerr** 2021-05-24 16:37 UTC

**Comment by kennykerr** [comment] 2021-08-12 04:53
This should now be working. Let me know if you experience any issues.
