### ISSUE TITLE
Link error when using WindowsProgramming::*

### ISSUE THREAD

**Issue by jquesada2016** [microsoft/windows-rs#967] opened 2021-07-09 23:27 UTC
# Issue
If you place the following within a bindings sub-crate (build.rs):
```rust
fn main() {
    windows::build!(
        Windows::Win32::System::WindowsProgramming::*
    );
}
```

and the try to use anything from the bindings crate:
```rust
use bindings::Windows::Win32::System; // For example

fn main() {}
```

you end up with a linking error. If you would like me to provide the error, please let me know. I didn't want to include it here because of the sheer size...

# Workaround
If instead of trying to build `WindowsProgramming::*`, you instead try to build against a specific function, i.e. `WindowsProgramming::GetComputerName`, then everything works.

### Extra Details
I am using `windows` crate on the current latest version, `0.17.2`, on Windows 10.

**Comment by kennykerr** [comment] 2021-07-09 23:37
Thanks for reporting. This is a duplicate of #463.

**Closed by kennykerr** 2021-07-09 23:37 UTC
