### ISSUE TITLE
Error message tests can't succeed on non-English systems

### ISSUE THREAD

**Issue by fghzxm** [microsoft/windows-rs#808] opened 2021-05-18 02:39 UTC
Unit tests `result::error_code::tests::test_message` and `result::error::tests::test_message` hard-code English-language error messages, and thus cannot succeed on non-English language systems:

```
> cargo test
...
---- result::error_code::tests::test_message stdout ----
thread 'result::error_code::tests::test_message' panicked at 'assertion failed: `(left == right)`
  left: `"操作成功完成。"`,
 right: `"The operation completed successfully."`', src\result\error_code.rs:159:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- result::error::tests::test_message stdout ----
thread 'result::error::tests::test_message' panicked at 'assertion failed: `(left == right)`
  left: `"操作成功完成。"`,
 right: `"The operation completed successfully."`', src\result\error.rs:177:9
```

**Comment by fghzxm** [comment] 2021-05-18 02:48
(Sorry for the havoc; I accidentally hit Enter when I was trying to enter the apostrophe)

**Comment by rylev** [comment] 2021-05-19 10:35
This is a duplicate of https://github.com/microsoft/windows-rs/issues/264. Again it's unfortunate, but since the only test that really matters at the end of the day is the CI test, and it will be set to English, it might not be worth the effort to localize the tests. That being said, if you come up with a way to easily make the tests pass on non-English systems, we'd be happy to accept a PR.

**Closed** 2021-05-19 15:10 UTC
