### ISSUE TITLE
CONTEXT isn't 16b aligned

### ISSUE THREAD

**Issue by 0vercl0k** [microsoft/windows-rs#2641] opened 2023-09-01 01:23 UTC
### Summary

The `windows::Windows::Win32::System::Diagnostics::Debug::CONTEXT` structure isn't annotated with `align(16)` like in the original C structure:
```rust
#[repr(C)]
#[doc = "*Required features: `\"Win32_System_Diagnostics_Debug\"`, `\"Win32_System_Kernel\"`*"]
#[cfg(target_arch = "x86_64")]
#[cfg(feature = "Win32_System_Kernel")]
pub struct CONTEXT {
// ...
}
```
```C
typedef struct DECLSPEC_ALIGN(16) DECLSPEC_NOINITALL _CONTEXT {
// ...
};
```

This causes issues when passing a `CONTEXT` to function like `GetThreadContext` for example (which expects the structure to be placed at a 16b aligned location).

I've looked through the repository and didn't find any existing conversation - am I missing something?

Cheers

**Comment by ChrisDenton** [comment] 2023-09-01 01:33
The windows-rs crate is generated from the [win32metadata](https://github.com/microsoft/win32metadata) project. For `CONTEXT` see this issue: https://github.com/microsoft/win32metadata/issues/1044

**Comment by 0vercl0k** [comment] 2023-09-01 02:56
Ha this makes more sense - I couldn't believe to be the first to hit this. Feel free to close this issue if tracking it is better in the other repo.

Cheers

**Comment by ChrisDenton** [comment] 2023-09-01 03:09
No problem. Closing as a duplicate of the upstream issue.

**Closed by ChrisDenton** 2023-09-01 03:09 UTC
Labels: bug
