### ISSUE TITLE
Windows Communication DCB dismiss fOutxCtsFlow fOutxDsrFlow fOutX fInX etc field. 

### ISSUE THREAD

**Issue by Richyeoh** [microsoft/windows-rs#3158] opened 2024-07-10 14:53 UTC
### Suggestion

Windows Communication DCB dismiss fOutxCtsFlow fOutxDsrFlow fOutX fInX etc field.

**Comment by Richyeoh** [comment] 2024-07-10 14:55
## Here is winbase.h code
```cpp
typedef struct _DCB {
  DWORD DCBlength;
  DWORD BaudRate;
  DWORD fBinary : 1;
  DWORD fParity : 1;
  DWORD fOutxCtsFlow : 1;
  DWORD fOutxDsrFlow : 1;
  DWORD fDtrControl : 2;
  DWORD fDsrSensitivity : 1;
  DWORD fTXContinueOnXoff : 1;
  DWORD fOutX : 1;
  DWORD fInX : 1;
  DWORD fErrorChar : 1;
  DWORD fNull : 1;
  DWORD fRtsControl : 2;
  DWORD fAbortOnError : 1;
  DWORD fDummy2 : 17;
  WORD  wReserved;
  WORD  XonLim;
  WORD  XoffLim;
  BYTE  ByteSize;
  BYTE  Parity;
  BYTE  StopBits;
  char  XonChar;
  char  XoffChar;
  char  ErrorChar;
  char  EofChar;
  char  EvtChar;
  WORD  wReserved1;
} DCB, *LPDCB;
```

##Here is windows for rust code
```rust
#[repr(C)]
pub struct DCB {

    pub DCBlength: [u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html),
    pub BaudRate: [u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html),
    pub _bitfield: [u32](https://doc.rust-lang.org/nightly/std/primitive.u32.html),
    pub wReserved: [u16](https://doc.rust-lang.org/nightly/std/primitive.u16.html),
    pub XonLim: [u16](https://doc.rust-lang.org/nightly/std/primitive.u16.html),
    pub XoffLim: [u16](https://doc.rust-lang.org/nightly/std/primitive.u16.html),
    pub ByteSize: [u8](https://doc.rust-lang.org/nightly/std/primitive.u8.html),
    pub Parity: [DCB_PARITY](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Devices/Communication/struct.DCB_PARITY.html),
    pub StopBits: [DCB_STOP_BITS](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Devices/Communication/struct.DCB_STOP_BITS.html),
    pub XonChar: [i8](https://doc.rust-lang.org/nightly/std/primitive.i8.html),
    pub XoffChar: [i8](https://doc.rust-lang.org/nightly/std/primitive.i8.html),
    pub ErrorChar: [i8](https://doc.rust-lang.org/nightly/std/primitive.i8.html),
    pub EofChar: [i8](https://doc.rust-lang.org/nightly/std/primitive.i8.html),
    pub EvtChar: [i8](https://doc.rust-lang.org/nightly/std/primitive.i8.html),
    pub wReserved1: [u16](https://doc.rust-lang.org/nightly/std/primitive.u16.html),
}
```

**Comment by Nerixyz** [comment] 2024-07-10 15:00
It's packed in `_bitfield` - note that bitfields aren't supported yet: https://github.com/microsoft/windows-rs/issues/2942.

**Comment by kennykerr** [comment] 2024-07-10 15:34
Closing as duplicate of #2942

**Closed by kennykerr** 2024-07-10 15:34 UTC
Labels: enhancement
