### ISSUE TITLE
Generate rust code/wrapper from (non-winrt) midl 

### ISSUE THREAD

**Issue by youyuanwu** [microsoft/windows-rs#1856] opened 2022-06-27 22:37 UTC
Hi team. I am from Azure ServiceFabric team and want to wrap our c sdk (idl based) to work well with windows-rs.

I followed https://github.com/kennykerr/component-rs to generate rust code from mdil but got error:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\wtypesbase.idl(468) : error MIDL2003 : [msg]redefinition [context]: _FLAGGED_WORD_BLOB
  C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\unknwnbase.idl(42) : error MIDL2003 : [msg]redefinition [context]: IUnknown
```
I showed my idl file to @kennykerr and he pointed out that my idl is not winrt and I need a work around.

Quote from kenny:
"Looks like you're not building a WinRT component. While it should in theory work for COM components as well, I haven't yet tested that and may require you to choose a different set of command line options for MIDL. Also MIDL has no ability to create a winmd file for non-WinRT components. I plan to support that natively in Rust (without IDL) and that's what I'm actively working on now, but its not there yet.
There's a tool you can use to do that today (produce a winmd for COM APIs) - but requires some build.rs scripting - until native support arrives. Rafael should be able to help you out if you open an issue.
"

**Comment by kennykerr** [comment] 2022-06-28 04:27
@riverar in case you have an example to point to.

**Comment by riverar** [comment] 2022-06-29 06:57
Hi @youyuanwu 👋,

I'm still in the process of documenting this process, but this should get you started.
https://github.com/riverar/washington-rs

[Email me](mailto:rafael@withinwindows.com) if you have questions and I'll try to get to them.

Closing as duplicate of #1518.

**Closed by riverar** 2022-06-29 06:57 UTC
Labels: question

**Comment by LoganDark** [comment] 2022-07-30 14:00
> I'm still in the process of documenting this process, but this should get you started.
> https://github.com/riverar/washington-rs

Is there anything we can just put in a build.rs? That manual code scares me, because if I adopted it then I'd have to maintain it and it looks like a mess.
