### ISSUE TITLE
`implement` custom attribute panicked with interfaces from local `binding` crate

### ISSUE THREAD

**Issue by bdbai** [microsoft/windows-rs#528] opened 2021-02-08 15:00 UTC
As I am trying out the `implement` feature to replace my hand-written WinRT implementations, I get an compilation error
```rust
#[::windows::implement(windows::ui::xaml::markup::IXamlType)]
pub struct XamlUserType {}
```
```rust
error[E0433]: failed to resolve: could not find `ui` in `windows`
 --> app\src\xaml_user_type.rs:9:1
  |
9 | #[::windows::implement(windows::ui::xaml::markup::IXamlType)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `ui` in `windows`
  |
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
I guess the argument for `implement` is used as a Rust type somewhere in the generated code, which exists in the `binding` mod. But the custom attribute panicked when I prepend `bindings::` to the argument
```rust
#[::windows::implement(bindings::windows::ui::xaml::markup::IXamlType)]
pub struct XamlUserType {}
```
```rust
error: custom attribute panicked
 --> app\src\xaml_user_type.rs:9:1
  |
9 | #[::windows::implement(bindings::windows::ui::xaml::markup::IXamlType)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: called `Option::unwrap()` on a `None` value
```

As a workaround, I have to import everything under `bindings` and use a fully-qualified syntax to refer to all members from `windows` crate.
```rust
use bindings::*;

#[::windows::implement(windows::ui::xaml::markup::IXamlType)]
pub struct XamlUserType {}
```

So how am I going to use `implement` correctly?

**Comment by kennykerr** [comment] 2021-02-08 15:45
Yes, the implement macro doesn't know which use declarations exist outside of the macro's input and it doesn't know the name of your bindings crate. It has to make certain assumptions, so it assumes it can find all the names in the local scope. This is not very intuitive, but it's the best I've come up with so far. Hopefully I can improve it in future.

**Comment by bdbai** [comment] 2021-02-08 16:13
What about providing an optional parameter for the prefix?

**Comment by kennykerr** [comment] 2021-02-09 20:50
I'll keep that in mind as I continue to work on this feature. I'd prefer not to clutter it with additional parameters, but it may come to that.

**Comment by kennykerr** [comment] 2021-04-20 23:36
Duplicate of #81

**Closed by kennykerr** 2021-04-20 23:36 UTC
Labels: question
