### ISSUE TITLE
Hstring from implementation for OsStr

### ISSUE THREAD

**Issue by arthmis** [microsoft/windows-rs#807] opened 2021-05-16 15:45 UTC
Can `HString` have a from implementation that converts `OsStr` to `HString`?

**Comment by kennykerr** [comment] 2021-05-24 16:15
Duplicate of #760

**Comment by kennykerr** [comment] 2021-05-24 16:37
Thanks for the feedback - that is something I'd like to support. I'll track it as part of #760

**Closed by kennykerr** 2021-05-24 16:37 UTC
