### ISSUE TITLE
OpenGL being included in windows.lib causes conflicts when compiling with OpenGL alternatives

### ISSUE THREAD

**Issue by monax3** [microsoft/windows-rs#1761] opened 2022-05-16 00:04 UTC
### Which crate is this about?

windows, windows-sys

### Crate version

0.36.1

### Summary

windows-rs can't be used together with directly linked ANGLE due to the OpenGL functions in windows.lib taking priority when linking

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Mona\.rustup

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
wasm32-wasi
x86_64-pc-windows-msvc
x86_64-unknown-linux-musl

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.62.0-nightly (70b3681bf 2022-05-14)

### Expected behavior

Successful linking without opengl32.dll being involved

### Actual behavior

  = note: lld-link: error: duplicate symbol: glGetError
          >>> defined at C:\Users\Mona\Tools\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\libGLESv2\libGLESv2_autogen.cpp:382
          >>>            libGLESv2.lib(libGLESv2_autogen.cpp.obj)
          >>> defined at opengl32.dll

### Additional comments

I don't know if there's any linker arguments I could use to personally solve this so I had to rebuild windows.lib without OpenGL to make my application link.

**Comment by monax3** [comment] 2022-06-02 17:51
Maybe this should be its own issue, but it would be helpful as a temporary solution for the target crates (windows_x86_64_msvc in my case) to include a [links key](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) ("windows", presumably) so that the windows.lib location can easily be [overridden](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts).

**Comment by kennykerr** [comment] 2022-06-10 18:10
I realized I probably don't need to wait for the multi-crate solution to fix this. Instead of producing the `windows.lib` amalgamation, I can simply have the various target crates include individual lib files for each DLL. Presumably, if you're not using OpenGL imports from the `windows` crate then you won't get those import collisions because Rust won't direct the linker to include the DLL-specific lib from the target crates.

**Comment by monax3** [comment] 2022-06-10 21:25
That would indeed resolve this and any similar problem, thank you

**Comment by kennykerr** [comment] 2022-06-14 18:13
I'm just not convinced the Rust linker facilities are all that predictable. 😜 Do you have a minimal repro you can share? That way I can confirm this works before making any changes.

**Comment by kennykerr** [comment] 2022-07-05 18:00
There's also a renewed effort to get `raw-dylib` completed which should also make this problem go away, so I may just close this issue in favor of that. 

https://github.com/rust-lang/rust/issues/58713#issuecomment-1172691533

**Comment by kennykerr** [comment] 2022-07-07 20:35
Closing for now. Feel free to keep the conversation going if this is still an issue.

**Closed by kennykerr** 2022-07-07 20:35 UTC
Labels: bug
