### ISSUE TITLE
The field CallbackType in MINIDUMP_CALLBACK_INPUT does not correspond to index values in MINIDUMP_CALLBACK_TYPE

### ISSUE THREAD

**Issue by ke1satsu** [microsoft/windows-rs#1892] opened 2022-07-12 15:13 UTC
I am writing a callback routine for a MinidumpWritedump implementation, and wish to match on the CallbackType field. This field is currently a u32 and I'm unsure how to compare it to the various MINIDUMP_CALLBACK_TYPE constants that exists in windows-rs.

If you were to compare the callback type in C++ you would do it against either the name of the type in the enum or refer by index. For example, IsProcessSnapshotCallback or 16.

It looks like the constants are defined in the latter way, printing IsProcessSnapshotCallback shows that it's indeed MINIDUMP_CALLBACK_TYPE(16).

So I expected the field to return u32 in the range 0-20, so that I could then compare against the inner values of the constants. The values vary greatly however, far exceeding that range. A sample of values: 0, 476, 285216287, 720, 736, 8072.

I'm not sure that there is actually a bug here, I could very well be misunderstanding something here. I would however like to suggest that this field become a MINIDUMP_CALLBACK_TYPE in the future to make it easier to match against it.

Thanks!

**Comment by tim-weis** [comment] 2022-07-12 15:34
This looks like a duplicate of #1744. The issue is still there in the latest metadata (24.0.1-preview).

**Comment by kennykerr** [comment] 2022-07-12 15:37
Thanks Tim, then I'll close this as a duplicate.

**Closed** 2022-07-12 15:45 UTC

**Comment by tim-weis** [comment] 2022-07-12 15:54
I'd still suggest keeping either this issue or #1744 open, possibly with a "blocked" tag. Much as I understand that maintainers would like to move issues that aren't (immediately) actionable out of sight, clients still need to be aware the issue.

@riverar Did you make any progress on [this](https://github.com/microsoft/win32metadata/issues/870#issuecomment-1121613402)?
