### ISSUE TITLE
std::fmt format specifiers not working

### ISSUE THREAD

**Issue by ben-lichtman-msft** [microsoft/windows-rs#968] opened 2021-07-10 01:57 UTC
For at least some structs, the format specifiers seem to not work correctly.

For example - trying to debug print an instance of MONMSGSTRUCT with:
`println!("{:#x?}", data);`

yields:

```rust
MONMSGSTRUCT {
    cb: 112,
    hwndTo: HWND { Value: 787156 },
    dwTime: 192557406,
    hTask: HANDLE { Value: 13412 },
    wMsg: 992,
    wParam: WPARAM { Value: 1117204 },
    lParam: LPARAM { Value: -1065369362 },
    dmhd: DDEML_MSG_HOOK_DATA { uiLo: 49390, uiHi: 49279, cbData: 0, Data: [0, 0, 0, 0, 0, 0, 0, 0] },
}
```

(notice that the numbers are in decimal and not hexidecimal)

I'm guessing this is due to the Debug trait implementations not using the normal debug format builders?

I have not tested other format specifiers but I expect a similar result...

**Comment by kennykerr** [comment] 2021-07-10 02:12
Thanks for reporting, this is a duplicate of #439.

**Comment by riverar** [comment] 2021-07-10 19:16
Fixed in master, give it a whirl!

**Closed by riverar** 2021-07-10 19:16 UTC
