### ISSUE TITLE
Functions that set last error could return `Result<T, crate::result::error>`

### ISSUE THREAD

**Issue by ryancerium** [microsoft/windows-rs#1105] opened 2021-09-01 04:14 UTC
You can do it for the different return types as long as the function metadata has `SetLastError=true`.  Here's my suuuuuuper simple implementation.  I think you would need to change it to return a `Result<T, result::error>`, and then re-implement `HRESULT_FROM_WIN32` in Rust accordingly:

```rust
pub trait Win32ReturnIntoResult
where
    Self: Sized,
{
    fn into_result(self) -> eyre::Result<Self>;
}

impl Win32ReturnIntoResult for BOOL {
    fn into_result(self) -> eyre::Result<BOOL> {
        match self.as_bool() {
            false => Err(std::io::Error::last_os_error().into()),
            _ => Ok(self),
        }
    }
}

impl Win32ReturnIntoResult for HANDLE {
    fn into_result(self) -> eyre::Result<HANDLE> {
        match self.is_invalid() {
            true => Err(std::io::Error::last_os_error().into()),
            _ => Ok(self),
        }
    }
}

impl Win32ReturnIntoResult for HHOOK {
    fn into_result(self) -> eyre::Result<HHOOK> {
        match self.is_null() {
            true => Err(std::io::Error::last_os_error().into()),
            _ => Ok(self),
        }
    }
}
```

**Comment by riverar** [comment] 2021-09-01 05:21
Hey @ryancerium. Just want to double-check my understanding.

I believe you are suggesting that functions with SetLastError/GetLastError semantics (indicated in upstream metadata with the `SetLastError` attribute) be generated with `Result<T, result::error>`. So for example, `SetWindowsHookEx` rather than return an `HHOOK`, it would return a `windows::Result<HHOOK>` or similar.

Sound right? (Sounds like a reasonable idea, too.)

**Comment by ryancerium** [comment] 2021-09-01 16:18
Oh dear.  I did the typical programmer thing of blasting you with code instead of actually describing my idea!  Yes, having `SetWindowsHookEx` return a `windows::Result<HHOOK>` or something like that is the idea.

The downside is perhaps the runtime cost of doing the error checking and calling `GetLastError`, but maybe forcing people into error checking wouldn't be such a bad thing?

Here's my wrapper of `CreateWindowExW`.  It would be better to make the windows-rs Rust function return the idiomatic `Result` itself instead of pushing that up into the client code.  The next step might be figuring out if the `unsafe` is still necessary, or if it could be wrapped as well during the generation.

```rust
impl Win32ReturnIntoResult for HWND {
    fn into_result(self) -> eyre::Result<Self> {
        match self.is_null() {
            true => Err(std::io::Error::last_os_error().into()),
            _ => Ok(self),
        }
    }
}

pub fn create_window<'a>(
    dwexstyle: WINDOW_EX_STYLE,
    lpclassname: impl IntoParam<'a, PWSTR>,
    lpwindowname: impl IntoParam<'a, PWSTR>,
    dwstyle: WINDOW_STYLE,
    x: i32,
    y: i32,
    nwidth: i32,
    nheight: i32,
    hwndparent: HWND,
    hmenu: HMENU,
    hinstance: HINSTANCE,
    lpparam: *mut c_void,
) -> eyre::Result<HWND> {
    unsafe {
        CreateWindowExW(
            dwexstyle,
            lpclassname,
            lpwindowname,
            dwstyle,
            x,
            y,
            nwidth,
            nheight,
            hwndparent,
            hmenu,
            hinstance,
            lpparam,
        )
        .into_result()
    }
}
```

**Comment by tim-weis** [comment] 2021-09-09 13:30
The `SetLastError` attribute is really a CLR-only attribute, that doesn't carry much useful information for anyone who isn't the P/Invoke marshaler.

Plus, this being the Windows API, there are going to be some interesting edge cases. [GetFileSize](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfilesize), for example, isn't going to be very easy to fit into this scheme (I'm sure, there are others).

This is not to say that I wouldn't welcome a more ergonomic interface. I'm just concerned about whether this can be done, or whether the `SetLastError` attribute can safely be used to direct code generation here.

**Comment by riverar** [comment] 2021-09-09 19:18
@tim-weis Upstream metadata is using this attribute today to indicate APIs that follow "this API sets last error" semantics. So the ask here is just that we do something smarter when we see that attribute.

Looking at the docs for `GetFileSize`, I'm not envisioning an immediate ergonomics issue but will admit my coffee cup is still fresh. What issue are you predicting with `GetFileSize(...) -> windows::Result<DWORD>`?

**Comment by ryancerium** [comment] 2021-09-09 20:25
A better example is [GetMessageW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagew) which returns a `BOOL` that is `0` if it was a `WM_QUIT` message, `-1` on error, and anything else on success.  Those are not the queen's booleans there.

[GetWindowLongPtrW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlongptrw) and [GetWindowTextLengthW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowtextlengthw) also have slightly more complex semantics where a 0 return may be valid, but you have to call `SetLastError()` beforehand and `GetLastError()` afterwards to find out.

**Comment by tim-weis** [comment] 2021-09-10 06:07
@riverar The core issue with repurposing the `SetLastError` attribute is, that it lacks semantic information. In case of `GetFileSize`, the result of calling `GetLastError` is only meaningful if the function returned `0xFFFF_FFFF`. The issue isn't about ergonomics but correctness.

Ryan provided good examples. Likewise complex as the latter one is [EnumWindows](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumwindows), where the implementer of the callback procedure is responsible for setting the error code in case of early termination.

The `SetLastError` attribute really has a single use-case: Instruct the CLR marshaler to cache the last error code so that managed code can later access, if it needs to. A boolean attribute is sufficient for this purpose. It's rather insufficient as a base for more complex decisions (which would be needed here).

**Comment by riverar** [comment] 2021-09-10 06:22
@tim-weis Ah, am aligned with you now. Thanks. In other words, the `windows::Result` would be invalid in success scenarios (and other cases where SetLastError isn't called).

**Comment by ryancerium** [comment] 2021-09-10 16:32
@riverar Do you know if the `SetLastError` metadata field is populated by parsing the Win32 headers or is it been manually entered for each of the 10,000 functions in the Win32 API?  I'm curious if there's a way to determine which functions would need more advanced error handling and which ones could do the simple thing.

**Comment by riverar** [comment] 2021-09-10 16:46
@ryancerium It's emitted into metadata as a result of [drumroll] parsing a hardcoded list https://github.com/microsoft/win32metadata/blob/b90be05f2911ce2af6aa3842390109b2d237ba44/generation/scraper/WithSetLastError.rsp

Not sure how the metadata folks build that file (hopefully not by hand). Perhaps they use some fuzzy scanner, looking for any SetLastError calls in the function block. @sotteson1 would probably have more insight.

**Comment by kennykerr** [comment] 2021-09-10 22:01
In general, I don't think this bit is useful unless the metadata also includes information on how to determine what "success" means for each API.

**Comment by ryancerium** [comment] 2021-09-10 22:20
@riverar Nothing I see about that file is super encouraging to it being a fuzzy scanner :-D

https://github.com/microsoft/win32metadata/issues/537
https://github.com/microsoft/win32metadata/commit/0992cabd9f7d44c5375d133a44ddf18c17a4d694
https://github.com/microsoft/win32metadata/commit/b90be05f2911ce2af6aa3842390109b2d237ba44

A good intern project might be to use a sentiment detector on the documentation, but otherwise you definitely would need something like what @kennykerr just mentioned for what the success and failure value are so that you could intelligently convert to an `Error` when necessary.  Then again, this might be a great opportunity to unify the return value documentation so that it's consistent and easy to parse.

When I opened the ticket I hadn't run across the horrors of multi-valued `BOOL`s yet.  They're just true and false, right?  right? riiiiiight...

**Comment by tim-weis** [comment] 2021-09-11 13:06
Ternary `BOOL`s aren't the issue here. The issue is that the `SetLastError` attribute merely means: Clients may need to know the last error code at some point. It expressly does not make any statement about the conditions under which clients may need to know.

This attribute is only meaningful in situations, where returning values to clients may itself clobber the calling thread's last error code. .NET's P/Invoke marshaler is the only case I know of where this needs to be done. It is still up to client code to only use the value when it is meaningful, on a case-by-case basis. The `SetLastError` attribute does not help identify the conditions under which the last error code is meaningful (it's not as simple as distinguishing between success and failure).

**Comment by kennykerr** [comment] 2021-09-11 15:14
The CLR provides special handling here since code may execute following the API call that would invalidate the last error stored on the thread, but this is not a problem that languages like C++ or Rust have to deal with. Keep in mind that the win32 metadata is not specific to .NET but is meant to convey information about APIs for all languages. Anyway, @sotteson1 can confirm what it is meant to indicate.

**Comment by sotteson1** [comment] 2021-09-13 16:46
FYI: The file that contains the list of APIs that call SetLastError was generated by scraping the docs since that information isn't available in the headers. The last few changes to the file were some false positives that made it into the list.

**Comment by sotteson1** [comment] 2021-09-13 17:09
> The CLR provides special handling here since code may execute following the API call that would invalidate the last error stored on the thread, but this is not a problem that languages like C++ or Rust have to deal with. Keep in mind that the win32 metadata is not specific to .NET but is meant to convey information about APIs for all languages. Anyway, @sotteson1 can confirm what it is meant to indicate.

SetLastError means the API calls SetLastError, as per the docs for that API. Language projections can do what they want with that bit of information, including ignoring it.

**Comment by ryancerium** [comment] 2021-09-13 23:45
So in order to do what I want, we'd also need to know the error value for a given function.

```C#
[ErrorValue(-1), SetLastError]
GetMessageW
```

So that this project could generate code like:
```Rust
pub fn get_message(msg: &mut MSG, hwnd: HWND, wmsgfiltermin: u32, wmsgfiltermax: u32) -> windows::Result<BOOL> {
    unsafe {
        match GetMessageW(msg, hwnd, wmsgfiltermin, wmsgfiltermax) {
            BOOL(-1) => Err(HRESULT_FROM_WIN32(GetLastError())),
            result => Ok(result),
        }
     }
}
```

But the necessary information, what value indicates an error, is very difficult to parse from documentation.  Bummer.

**Comment by tim-weis** [comment] 2021-09-14 13:48
@sotteson1 Is [HeapAlloc](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc) being on [the list](https://github.com/microsoft/win32metadata/blob/5e3f42421994b77e41ccfba84739fb78cdc13b8d/generation/scraper/WithSetLastError.rsp) an oversight, or is there more to the `SetLastError` attribute?

**Comment by ryancerium** [comment] 2021-09-14 16:17
@tim-weis That looks like another false positive.  You should open a ticket in the win32metadata project.

**Comment by kennykerr** [comment] 2021-09-14 21:18
There isn't anything actionable here for me to work on, and I doubt the win32 metadata will annotate every API with the necessary information to make that work, so I'm going to close this. In general, Win32 APIs like those affected by this issue should be dealt with by writing an idiomatic Rust library crate that provides the necessary smarts.

**Closed by kennykerr** 2021-09-14 21:18 UTC
Labels: enhancement
