### ISSUE TITLE
Document naming translation conventions

### ISSUE THREAD

**Issue by Serentty** [microsoft/windows-rs#425] opened 2021-01-22 01:30 UTC
Right now, it seems like WinRT-based APIs have their names converted to match Rust naming conventions, whereas Win32 ones do not. This is an unfortunate style mismatch. It would be nice if all APIs could follow the same idiomatic naming conventions.

**Comment by Lokathor** [comment] 2021-01-22 02:29
I would say go the other directions: all raw function declarations should use precisely the original name, and leave the snake_case conversion to wrapper crates or whatever higher level thing people care to use.

**Comment by kennykerr** [comment] 2021-01-22 05:35
Indeed, this is by design. The WinRT subset is converted in such a way as to appear idiomatic because it is a rich wrapper over the underlying ABI. The remaining Win32, and to some degree COM, APIs preserve their original names because they are largely direct calls to the ABI and typically need wrapping of some kind before they can be used idiomatically in Rust.

**Comment by rylev** [comment] 2021-01-22 09:34
It's also idiomatic for bindings for C APIs (which win32 APIs are) retain their original casing. The WinRT APIs exposed by windows-rs are wrappers and meant to be (relatively) idiomatic. They call underlying foreign functions but are Rust APIs themselves and thus deserve Rust idiomatic camel casing. I think we can close this issue.

**Comment by Lokathor** [comment] 2021-01-22 13:54
Slow down one moment: What you just said should be put into the readme and at the root level of the crate documents so that people understand what's going on with that.

**Comment by rylev** [comment] 2021-01-22 13:56
Sorry! Didn't mean to close prematurely. Happy to put this in the README! ❤️

**Comment by rylev** [comment] 2021-04-09 14:58
Names are no longer converted, so closing this.

**Closed by rylev** 2021-04-09 14:58 UTC
Labels: documentation

**Comment by Serentty** [comment] 2021-04-20 18:58
@rylev That's interesting. What was the rationale for that? Were misconversions common enough that you decided it wasn't worth the trouble?

**Comment by kennykerr** [comment] 2021-04-20 19:16
https://github.com/microsoft/windows-rs/pull/646
