### ISSUE TITLE
The build should test x86, x64, nightly, and stable

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#522] opened 2021-02-05 17:13 UTC
Currently it only builds x64 and there may be x86 issues that go undetected. For example, these functions are only available for x64 builds:

https://github.com/microsoft/windows-rs/blob/bf5efbf4933e3e44ff9322735065fa88d64d281c/examples/clock/src/main.rs#L724-L729

We need to use `GetWindowLongA` and `SetWindowLongA` for x86 builds.

**Comment by kennykerr** [comment] 2021-02-11 20:10
The build should perhaps also run nightly and stable, not just stable.

**Comment by kennykerr** [comment] 2021-03-11 17:04
Blocked on https://github.com/rust-lang/rust/issues/82991

**Comment by rylev** [comment] 2021-03-15 12:40
I've not yet been able to find the root cause of the issue in rustc, but it seems to be an issue from the renaming of the crate in the Cargo.toml file. If you change `windows_gen` Cargo.toml file to specify `windows_gen_macros` like so `windows_gen_macros = { path = "macros",  version = "0.4.0" }` and rename all instances of `macros` to `windows_gen_macros` inside the `windows_gen` crate, the code compiles with `cargo +nightly build --target=i686-pc-windows-msvc`. 

Of course, the issue in rustc should be fixed so it's up to you whether you want to implement the workaround or wait until the compiler is fixed.

**Closed** 2021-03-22 18:58 UTC
Labels: blocked, enhancement
