### ISSUE TITLE
Upgrading `windows-targets` from v0.48.1 to v0.48.2 breaks build on `pc-windows-gnu`

### ISSUE THREAD

**Issue by V0ldek** [microsoft/windows-rs#2642] opened 2023-09-02 00:38 UTC
### Summary

This is a weird one, so sorry if I'm ruining your day just now.

I was performing a routine `cargo update` in my open-source project which resulted in the build pipeline failing on the `i686-windows-pc-gnu` and `x86_64-windows-pc-gnu` targets. The error is a gigantic trace of the linker flipping its junk over unrecognised `.drective --exclude-symbols:` and corrupt `.drective` at end of file. You can see the [workflow run here](https://github.com/V0ldek/rsonpath/actions/runs/6054746186/job/16432668009), or the full raw logs ([Test matrix (stable, x86_64-pc-windows-gnu-nosimd).zip](https://github.com/microsoft/windows-rs/files/12502114/Test.matrix.stable.x86_64-pc-windows-gnu-nosimd.zip)), see `12_Build without simd` for the error) . Here's the head and tail of that log:

```ini
   Compiling clap v4.4.2
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rustc9IDm5Z\\symbols.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.00.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.01.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.02.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.03.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.04.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.05.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.06.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.07.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.08.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.09.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.10.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.11.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.12.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.13.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.14.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.rq.71b592de09118855-cgu.15.rcgu.o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.18ib94n1pmvm0cp4.rcgu.o" "-L" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps" "-L" "D:\\a\\rsonpath\\rsonpath\\target\\debug\\deps" "-L" "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\windows_x86_64_gnu-0.48.5\\lib" "-L" "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\windows_x86_64_gnu-0.42.2\\lib" "-L" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libsimple_logger-149b62e6a5343262.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libwindows_sys-d5a398412c27fb5c.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libtime-c2a19090f8e34c4e.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libitoa-650da94416a9f32d.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libtime_core-0de6f0899aab7776.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libderanged-ac61083620ca6da6.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libcolored-92e8bb199a530536.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\liblazy_static-b81769a4a62c4777.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libis_terminal-c85581ec9c9b2a68.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\librsonpath-21f150a11906dee7.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libstatic_assertions-4c8a6623f0d52770.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libnom-930dde77b4e0fd30.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libvector_map-f69b977b638b4c3b.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libmemmap2-025542a49252cc8e.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libsmallvec-e5039cfa95925f16.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libthiserror-9642019a6c55f1bf.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\liblog-4e7c0e0f1ac10fbe.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libcolor_eyre-6a0f7e332c57a746.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libowo_colors-a48bb57af77558b6.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libeyre-ffb1c3be35f92a06.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libindenter-e51afb8daa52dd1c.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libonce_cell-1ccd43150a31a5fe.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libbacktrace-81a81baf563b3707.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libobject-871fa2fd62222d0f.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libmemchr-113f3db420c7dde1.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\liblibc-bac02151d614165f.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libaddr2line-616ef336efd1ee46.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libgimli-817c6a41f84f6586.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libcfg_if-48ae00124042c8ff.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\librustc_demangle-4da9856eb7d1bb77.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libclap-c0a88ea952db5897.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libclap_builder-54ef5191658a0a52.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libterminal_size-9fad0353318ba8ad.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libstrsim-b3dc77cee1f2c13b.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libanstream-a635bf027a1bb320.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libanstyle_query-d1de31b3c7a27948.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libanstyle_wincon-e8417e7ca536dd6a.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libwindows_sys-1f0695c0156d3495.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libwindows_targets-3fb502f8f3c3e900.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libcolorchoice-7f40833bf8306e35.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libanstyle_parse-5831bf6424ae5dbc.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libutf8parse-95824640bb78651c.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libclap_lex-af6a6cbf1f63d651.rlib" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\libanstyle-b8eca0c8715a5bb6.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-274cab44dc4a644c.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-0f177752b9ca8e95.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-06bb167660b3da76.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr-8ab6cc09499ecf5b.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-126153ebe55b6775.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-3d08640ec0a90b99.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-e211ed0efcaf0dab.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_detect-f17f8b04b9a04cbd.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-dc505c5f7a08eb2f.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-29139547fec356ea.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libminiz_oxide-cab94e250dc1e17d.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libadler-e6226bb3d40532fc.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-bc036f0a729eca3e.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-b7a734954c1f5dcb.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-a254eeb9e90dc361.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-b6fb9ac972c98305.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-6db27a6ad3c9479a.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-6fcad14090edadfc.rlib" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-625af2eb18940f92.rlib" "-Wl,-Bdynamic" "-lwindows" "-lkernel32" "-lkernel32" "-lwindows.0.48.5" "-lkernel32" "-ladvapi32" "-lbcrypt" "-lkernel32" "-lntdll" "-luserenv" "-lws2_32" "-lkernel32" "-lws2_32" "-lkernel32" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-o" "D:\\a\\rsonpath\\rsonpath\\target\\x86_64-pc-windows-gnu\\debug\\deps\\rq-b14687b1b7837e24.exe" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17h047653d85284e3e1E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17h0fef515490bb0742E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17h3d816349e73c38a6E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17h4fd54a8982a0628eE" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17h60fb3fddb1c965fcE" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17hbf5ceed378bc3c91E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17hd7fc07c7332007f0E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17hdda702d32fa85391E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN127_$LT$rsonpath..engine..main..Executor$LT$I$C$R$GT$$u20$as$u20$rsonpath..engine..head_skipping..CanHeadSkip$LT$I$C$R$C$_$GT$$GT$14run_on_subtree17hed34b5f419982222E" ' unrecognized

< SNIP ... >

           Warning: .drectve `-exclude-symbols:_ZN4core5alloc6layout6Layout5array5inner17h44af3a9fb2a6c139E ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN63_$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$10deallocate17h28c7a71124b1f745E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN63_$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$15allocate_zeroed17ha5c92e80da5f73f7E" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN63_$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$4grow17h06a02bfbe47d784aE" ' unrecognized

          Warning: .drectve `-exclude-symbols:"_ZN63_$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$8allocate17hf2597eb0cc27383eE" ' unrecognized

          Warning: corrupt .drectve at end of def file

          Warning: corrupt .drectve at end of def file

          Warning: corrupt .drectve at end of def file

          Warning: corrupt .drectve at end of def file

          Warning: corrupt .drectve at end of def file

          Warning: corrupt .drectve at end of def file

          Warning: .drectve `-exclude-symbols:_ZN17compiler_builtins3int19specialized_div_rem12u128_div_rem17ha5b4b44252fd35fdE ' unrecognized

          Warning: .drectve `-exclude-symbols:_ZN17compiler_builtins3int19specialized_div_rem11u64_div_rem17h4d9b72e8c8903ff3E ' unrecognized

          Warning: corrupt .drectve at end of def file

          collect2.exe: error: ld returned 5 exit status
          

error: could not compile `rsonpath` (bin "rq") due to previous error
error: process didn't exit successfully: `\\?\C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe build --target x86_64-pc-windows-gnu --manifest-path crates\rsonpath\Cargo.toml --no-default-features` (exit code: 101)
```

The error is way above my paygrade. It happens during the compilation of `clap`, because that's the path to the `windows-targets` dependency in my project:

```ini
rsonpath v0.6.1
├── clap v4.4.2
│   ├── clap_builder v4.4.2
│   │   ├── anstream v0.5.0
│   │   │   ├── anstyle-query v1.0.0
│   │   │   │   └── windows-sys v0.48.0
│   │   │   │       └── windows-targets v0.48.5
│   │   │   │           └── windows_x86_64_gnu v0.48.5
[Test matrix (stable, x86_64-pc-windows-gnu-nosimd).zip](https://github.com/microsoft/windows-rs/files/12502114/Test.matrix.stable.x86_64-pc-windows-gnu-nosimd.zip)

```

Unfortunately this is about everything I am able to pin down. I wasn't able to replicate this issue independently. Creating a crate that references `clap` and building it, even using the same CLI interface as in my project but with the logic removed, does not reproduce the issue.

On my machine and in the GitHub runner, checking out the latest stable commit of https://github.com/V0ldek/rsonpath.git (`62a65f5b085785322c942e5f9e321c29639f1a08`), running `cargo update -p windows-targets` and then `cargo build --target` fails with the error above. Note that both me and the host runner are running Windows. On the other hand, when running the same steps in a clean `ubuntu:latest` Docker container the issue does not occur.

In any case, on a Windows machine the following steps seem to reproduce the issue:

```console
$ rustup target add x86_64-pc-windows-gnu
$ git clone https://github.com/V0ldek/rsonpath.git
$ cd rsonpath
$ git checkout 62a65f5b085785322c942e5f9e321c29639f1a08
$ cargo update -p windows-targets
    Updating crates.io index
    Updating windows-targets v0.48.1 -> v0.48.5
    Updating windows_aarch64_gnullvm v0.48.0 -> v0.48.5
    Updating windows_aarch64_msvc v0.48.0 -> v0.48.5
    Updating windows_i686_gnu v0.48.0 -> v0.48.5
    Updating windows_i686_msvc v0.48.0 -> v0.48.5
    Updating windows_x86_64_gnu v0.48.0 -> v0.48.5
    Updating windows_x86_64_gnullvm v0.48.0 -> v0.48.5
    Updating windows_x86_64_msvc v0.48.0 -> v0.48.5
$ cargo build --target x86_64-pc-windows-gnu
```

I know that this report is scarce in repro details, but I really am at a stump as to how to find the root cause. Any help is appreciated, please let me know what details I could provide to assist with this.

**Comment by ChrisDenton** [comment] 2023-09-02 00:56
This looks like a duplicate of #2614? The current solution to which is:

> Given this builds in binutils 2.41, it looks like it's already fixed. So at this point, I'd recommend using an external binutils suite as suggested above until the Rust gnu toolchain gets updated.

**Comment by ChrisDenton** [comment] 2023-09-04 17:29
Closing as duplicate.

**Closed by ChrisDenton** 2023-09-04 17:29 UTC
Labels: question
