### ISSUE TITLE
D3D11_TEXTURE2D_DESC wrong typing

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#2782] opened 2024-01-09 22:40 UTC
### Suggestion

It seems that most `D3D11_TEXTURE_D` structs don't use the correct types for some properties,
an example is `D3D11_TEXTURE2D_DESC`.

`CPUAccessFlags`  is `u32` instead of `D3D11_CPU_ACCESS_FLAG`
`MiscFlags`  is `u32` and I think it should be `D3D11_RESOURCE_MISC_FLAG`
`BindFlags`  is `u32` instead of `D3D11_BIND_FLAG`

Think these are the same for all `D3D11_TEXTURE_D_DESC` structs.

Not sure if it's wrong in the Meta or Rust, it looks correct here: https://github.com/microsoft/win32metadata/blob/1ba2527a59da3f1c1b4809bb053d03f300af3c09/generation/WinSDK/emitter.settings.rsp#L1388C16-L1388C16

**Comment by kennykerr** [comment] 2024-01-10 02:15
The struct is defined as follows in the Windows SDK:

```C++
typedef struct D3D11_TEXTURE2D_DESC
    {
    UINT Width;
    UINT Height;
    UINT MipLevels;
    UINT ArraySize;
    DXGI_FORMAT Format;
    DXGI_SAMPLE_DESC SampleDesc;
    D3D11_USAGE Usage;
    UINT BindFlags;
    UINT CPUAccessFlags;
    UINT MiscFlags;
    } 	D3D11_TEXTURE2D_DESC;
```

So that seems consistent with Rust. The metadata includes some extra information:

```C#
public struct D3D11_TEXTURE2D_DESC
{
	public uint Width;

	public uint Height;

	public uint MipLevels;

	public uint ArraySize;

	public DXGI_FORMAT Format;

	public DXGI_SAMPLE_DESC SampleDesc;

	public D3D11_USAGE Usage;

	[AssociatedEnum("D3D11_BIND_FLAG")]
	public uint BindFlags;

	[AssociatedEnum("D3D11_CPU_ACCESS_FLAG")]
	public uint CPUAccessFlags;

	[AssociatedEnum("D3D11_RESOURCE_MISC_FLAG")]
	public uint MiscFlags;
}
```

But that depends on the invented `AssociatedEnum` attributes that are not from the original API. I'm not a fan of the attribute as it's not very practical to use in a meaningful way in all of the places that it shows up. Here for example, I'd need to guarantee that the size of the associated enum is the same as the field itself. I also have to ensure that the unqualified enum name can be found. Perhaps this is useful for other languages, but it doesn't seem very useful in Rust.

**Comment by Zerowalker** [comment] 2024-01-10 07:46
Why wouldn't you want the associated `AssociatedEnum`?
You say it's not very practical, is it used in different places that are inconsistent or something?

If it's only used there (or in similar cases) isn't it a good thing?
Say `BindFlags`, if the only supported values for it is within `D3D11_BIND_FLAG`,
wouldn't enforcing that be a good thing (just like `Format` and `DXGI_FORMAT`)?

Also any reason why it's not actually it's own type originally like `Format`, kinda surprised that isn't the case.
Usually when it's not I just assume it's cause there might be extra values missing in the future or something,
so having it as a `uint` or something makes it compatible (kinda like `WM_..`  stuff isn't it's own type originally).

**Comment by kennykerr** [comment] 2024-01-10 11:56
It's related to what I discussed here: https://github.com/microsoft/windows-rs/issues/2784#issuecomment-1884705056

We need to be careful that the type does not affect the ABI for the struct layout. The code generator assumes there's some discrepancy and sticks to the original type for fields. In theory we could check whether the types have the same size and layout and if so then replace the underlying type with the alternative enum, even though the enum's underlying type is different.

**Comment by kennykerr** [comment] 2024-01-16 16:37
Closing as duplicate of #2784 to keep the conversation in one place.

**Closed by kennykerr** 2024-01-16 16:37 UTC
Labels: question

**Comment by MarijnS95** [comment] 2024-01-18 10:08
There's a similar example with `D3D12_RENDER_TARGET_BLEND_DESC::RenderTargetWriteMask`, which is a `u8`, while the `D3D12_COLOR_WRITE_ENABLE` flag is probably generated as `INT` by default.

One possible solution to the ABI problem is to generate a special `u8` version of the enum flag for these use-cases, with a natural conversion between the `INT` version while keeping things somewhat annotated and type safe. Or at the very least an intradoc comment stating the enum that should be used for an `AssociatedEnum` field?

The other approach is, in either `win32metdata` or `windows-rs`, since it knows where a type is used/associated: deduce whether all (associated) "uses" of an enum have the same type/ABI, and replace the `int`-inferred (https://github.com/microsoft/win32metadata/issues/1822#issuecomment-1894474350) enum type with that. May be very finicky and not very future-proof, though (but I've ran into a lot of flags that are specific to one or two structs and would benefit from this. Functions naturally don't have this problem as `windows-rs` generates a conversion).
