### ISSUE TITLE
UNICODE_STRING contains a PWSTR that points to a non-null-terminated string

### ISSUE THREAD

**Issue by micolous** [microsoft/windows-rs#2566] opened 2023-07-04 04:35 UTC
### Which crate is this about?

windows-sys

### Crate version

0.48.0

### Summary

Per [UNICODE_STRING documentation on MSDN][0] (emphasis added):

> `Buffer`
>
> Pointer to a wide-character string. Note that the strings returned by the various LSA functions **might not be null-terminated.**
>
> Windows 7, Windows Server 2008, Windows Vista, Windows Server 2003 and Windows XP:  When the Length structure member is zero and the MaximumLength structure member is 1, **the Buffer structure member can be an empty string or contain solely a null character**. This behavior changed beginning with Windows Server 2008 R2 and Windows 7 with SP1.

[0]: https://learn.microsoft.com/en-us/windows/win32/api/subauth/ns-subauth-unicode_string

And [STRING documentation on MSDN][1] (emphasis added):

> **If the string is null-terminated,** Length does not include the terminating NULL.

(ie: the value may not be null terminated)

[1]: https://learn.microsoft.com/en-us/windows/win32/api/ntdef/ns-ntdef-string

At the moment, the `UNICODE_STRING::Buffer` member is declared as a `PWSTR`:

https://github.com/microsoft/windows-rs/blob/fa7b52473eebad0deb8e561bfc893df22f283999/crates/libs/sys/src/Windows/Win32/Foundation/mod.rs#L20342-L20345

And `STRING::Buffer` is a `PSTR`:

https://github.com/microsoft/windows-rs/blob/fa7b52473eebad0deb8e561bfc893df22f283999/crates/libs/sys/src/Windows/Win32/System/Kernel/mod.rs#L559-L562

`PWSTR` assumes it is pointing to a null-terminated array, and uses `wcslen` to find the length:

https://github.com/microsoft/windows-rs/blob/fa7b52473eebad0deb8e561bfc893df22f283999/crates/libs/core/src/strings/pwstr.rs#L34-L36

`PSTR` does the same but with `strlen`:

https://github.com/microsoft/windows-rs/blob/fa7b52473eebad0deb8e561bfc893df22f283999/crates/libs/core/src/strings/pstr.rs#L34-L36

Both of these functions cannot check the `Length`, so [have buffer overrun issues][3]:

> **Security Note** These functions incur a potential threat brought about by a buffer overrun problem. Buffer overrun problems are a frequent method of system attack, resulting in an unwarranted elevation of privilege. For more information, see [Avoiding buffer overruns](https://learn.microsoft.com/en-us/windows/win32/SecBP/avoiding-buffer-overruns).

[3]: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strlen-wcslen-mbslen-mbslen-l-mbstrlen-mbstrlen-l?view=msvc-170

### Toolchain version/configuration

% rustup show
Default host: x86_64-apple-darwin
rustup home:  ~/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

thumbv6m-none-eabi
wasm32-unknown-unknown
x86_64-apple-darwin
x86_64-pc-windows-gnu <-- using this target
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.70.0 (90c541806 2023-05-31)

### Reproducible example

```rust
use windows::core::{PSTR, PWSTR};
use windows::Win32::Foundation::UNICODE_STRING;
use windows::Win32::System::Kernel::STRING;

fn main() {
    let mut hello = [104u16, 101, 108, 108, 111, 33];
    let u = UNICODE_STRING {
        Length: 10,
        MaximumLength: 12,
        Buffer: PWSTR(hello.as_mut_ptr()),
    };

    let mut world = [119u8, 111, 114, 108, 100, 33];
    let s = STRING {
        Length: 5,
        MaximumLength: 6,
        Buffer: PSTR(world.as_mut_ptr()),
    };

    // These are unsafe conversions because they don't use the Length parameter
    println!("{}", unsafe { u.Buffer.to_string().unwrap() });
    println!("{}", unsafe { s.Buffer.to_string().unwrap() });

    // Use length parameter
    let u = String::from_utf16(unsafe { std::slice::from_raw_parts(u.Buffer.0, u.Length.into() / 2) })
        .unwrap();
    let s = std::str::from_utf8(unsafe { std::slice::from_raw_parts(s.Buffer.0, s.Length.into()) })
        .unwrap();
    println!("{u} {s}");
}
```

### Crate manifest

```toml
[package]
name = "windows-strings"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.48.0", features = ["Win32_System_Kernel", "Win32_Foundation"] }
```

### Expected behavior

* the `Buffer` field should be a `*mut` pointer, not a `PSTR` / `PWSTR`.
* `STRING` and `UNICODE_STRING` should be wrapped similar to what [this crate does for `HSTRING`][2] to provide safe conversions to Rust `String` types

because using `Buffer.to_string()` with these is not correct!

[2]: https://github.com/microsoft/windows-rs/blob/master/crates/libs/core/src/strings/hstring.rs

### Actual behavior

EDITED: fixed code example's `UNICODE_STRING::Length` to be a length in bytes, rather than UTF-16 codepoints, and extended `MaximumLength`. Added note about raw pointers.

**Comment by riverar** [comment] 2023-07-04 16:59
Hey @micolous, `PWSTR::as_wide`, `PSTR::as_bytes`, and `PWSTR::to_string` are already marked unsafe; those functions assume you're working with null-terminated strings, which is the common use case across the Win32 API space. There are definitely some gotchas when dealing with non-null-terminated strings though that we're discussing. (Be aware it's a holiday week so things may move slower than expected.)

**Comment by kennykerr** [comment] 2023-07-06 13:26
Yes, there's nothing "wrong" with the bindings - as @riverar points out the code is clearly unsafe so there's your clue. 

I think @tim-weis is also right that the metadata could be improved, and I have some plans to make that a lot simpler to rectify.

**Comment by riverar** [comment] 2023-07-06 14:59
> that same member also re-uses the PWSTR type, which is implied to be null terminated

Remember though, PWSTRs may or may not be null terminated too.

**Comment by tim-weis** [comment] 2023-07-06 15:28
@riverar Well, no. `PWSTR`'s have the `_Null_terminated_` SAL annotation. They are *always* assumed to be null terminated. That's in contrast to `PWCH`, a type that aliases the same underlying type, but doesn't have the `_Null_terminated_` attribute.

This is how (I presume) things are designed. Not going to comment on how things turn out in  practice. YMMV, I guess.

On a more personal, while I have your attention already: Love your contributions, here, and elsewhere. You're an absolute animal! Much like Kenny, who's someone/"something" I cannot name without falling victim to blasphemy.

Thank you both. You've provided me with powerful tools that make my life easier, and a feeling of confidence, that it's not just me who [*"give\[s\] a damn"*](https://www.facebook.com/permalink.php?story_fbid=pfbid0iPixEvPJQGzNa6t2x6HUL5TYqfmKGqSgfkBg6QaTyHF5frXQi7eLGxC7uPQv5U5jl&id=100006735798590&__cft__[0]=AZXsDdV3k6gSu83P0a2jJg4FQsWHW-usRsi2ayd7dymrA9C6yBA-uWSUgw7A8Mhza8gpZFkCvbip_sJRxDvUMP273PIS0FOSQQWGmL2Cbv3HVg&__tn__=%2CO%2CP-R).

**Comment by micolous** [comment] 2023-07-07 06:59
> `PWSTR::as_wide`, `PSTR::as_bytes`, and `PWSTR::to_string` are already marked unsafe per the SAFETY blocks.

I understand the intended use of those types is that they _always_ contain null-terminated data, and that's even documented on the Rust side:

https://github.com/microsoft/windows-rs/blob/fa7b52473eebad0deb8e561bfc893df22f283999/crates/libs/core/src/strings/pstr.rs#L3

https://github.com/microsoft/windows-rs/blob/fa7b52473eebad0deb8e561bfc893df22f283999/crates/libs/core/src/strings/pwstr.rs#L3

_I don't think there's anything wrong with those types, nor the safety notes they have on their helper methods._ My intent in mentioning those functions was to give code examples which depended on that assumption, thus forming a sort of API contract.

Because `STRING` and `UNICODE_STRING` explicitly state that `Buffer` might _not_ be null-terminated (and also, the buffer may exceed the `Length` of the string, as in my example), it _explicitly_ violates the contracts of the `PSTR` and `PWSTR` types (at minimum, on a `windows-rs` level), and (with a Type Police hat on) _is a bug to use those types in this crate's public interface_.

On the Rust side, `*mut` pointers would be better, because then you _don't_ get any added functionality[^1] incorrectly using `strlen` or `wcslen`, and as a developer, you're forced to consider "what am I actually getting?".

My angle here is that the easiest path should be the safe (or "least unsafe") one. The less special cases a developer needs to remember, the better.

> In essence, all the information to generate a safer Rust API is available, even if presented in a weird, roundabout way. Short term, it might be worth evaluating whether transforming a `[NotNullTerminated] PWSTR` back into a `PWCH` (and adding a less thorny API for this type) is useful and maintainable.

I wasn't aware there was machine-readable metadata for that attribute, but yeah, this would make it easier to fix if other types have the same issue.

> Yes, there's nothing "wrong" with the bindings - as @riverar points out the code is clearly unsafe so there's your clue.

Currently, `windows-rs` gives you an interface, which, thanks to convenience methods intended to make string handling easier[^1], is _trivial_ hurt yourself with. The only way you know there _could_ be a problem is if you develop with the presumption `windows-rs` types are entirely wrong, and check what MSDN says.

By contrast, Rust itself and `winapi-rs` also define those structs:

https://github.com/rust-lang/rust/blob/bb548f964572f7fe652716f5897d9050a31c936e/library/std/src/sys/windows/c/windows_sys.rs#L3959-L3964

https://github.com/retep998/winapi-rs/blob/5b1829956ef645f3c2f8236ba18bb198ca4c2468/src/um/subauth.rs#L9-L19

Except in those crates, `PWSTR` and `PCHAR` are simple `*mut` pointers. If a developer chooses to use that `*mut` pointer with `wcslen` or `strlen`, they would do so in their own code, and that's their own fault if it goes wrong.

[^1]: Which again, I acknowledge these convenience methods are marked `unsafe fn`. 😄

**Comment by micolous** [comment] 2023-07-07 07:52
And after re-reading my initial report, I can see how you might have read this as I'm reporting a bug in `PSTR` and `PWSTR`. I've edited that a little now to hopefully make things clearer.

My original angle was that `STRING` and `UNICODE_STRING` should have explicit `String` conversion functions, like `HSTRING`, which were implemented correctly (by using the `Length` field), rather than using `Buffer::to_string()` which is totally wrong.

**Comment by tim-weis** [comment] 2023-07-08 11:13
> Not sure I trust SAL markup, we've come across our fair share of errors already. And Microsoft documents otherwise! (Surprise!) https://learn.microsoft.com/openspecs/windows_protocols/ms-dtyp/50e9ef83-d6fd-4e22-a34a-2c6b4e3c24f3

@riverar I'm not sure that there were *anything* more trust-worthy than SAL annotations in the Windows SDK. They are tool-verified, and it is my understanding that a version of Windows will not ship if any implementation fails to conform to the contractual guarantees encoded in the SAL annotations.

If OpenSpec disagrees with the ground truth (that is, the shipped SDK header files), then that is something that team, and their lawyers have to address. I doubt that this could ever mean for the SDK team to change shipped header files.

**Comment by kennykerr** [comment] 2023-07-10 13:13
Closing as there's no actionable work here for windows-rs but feel free to keep the conversation going.

**Comment by kennykerr** [comment] 2023-07-13 14:45
Yep, I have plans to stabilize metadata through the `riddle` tooling that I'm working on this year. It should make it a lot easier to deal with issues like this as we can define it canonically without a roundtrip through the win32metadata machinery.

**Comment by micolous** [comment] 2023-07-17 04:36
> Closing as there's no actionable work here for windows-rs

@kennykerr, while this issue may not be `windows-rs`' "fault", I believe there are three actions which could taken to mitigate or address this issue (which I've ordered from crude to elegant/elaborate):

1. Special-case the `Buffer` fields into `*mut` pointers (like Rust itself and `winapi-rs` already do, [as noted above][0]), which would remove the `x.Buffer.to_string()` trap.

2. Provide alternative `to_string()` methods for `STRING` and `UNICODE_STRING` which use the `Length` field correctly (like `HSTRING`), which would gently guide the developer towards doing the right thing.

3. Consume the `NotNullTerminated` attribute; though I suspect `STRING` and `UNICODE_STRING` would also need safe wrappers anyway. From what you've described, while it's a better solution, it seems more complex to implement, and would be better served in a wider-scope issue.

At the moment, the `Buffer` field of those two types "as exposed" by `windows-rs` is incorrect, and leads to subtle programming errors.  It's not clear to me how much of the Win32 API deals in _unterminated_ `STRING` and `UNICODE_STRING` (as I don't have Windows source access), but shifting the responsibility to third-party developers (when they're using a first-party-endorsed/provided interface) isn't a particularly nice experience, especially when they're expected to not introduce new bugs to the platform or depend on undocumented behaviour.

Thanks! 😄 

[0]: https://github.com/microsoft/windows-rs/issues/2566#issuecomment-1624850570

**Comment by micolous** [comment] 2023-07-17 04:54
PS: I'm happy to have a chat offline with yourself or other folks about this, because there's probably some context or details to this that I don't have which you do, or vice versa; and that might be be faster than going through bugs on this.

**Comment by riverar** [comment] 2023-07-17 08:03
Fair. `PWSTR` holds a pointer to a null-terminated string. It having _unsafe_ utility functions is not a bug. `UNICODE_STRING` contains a `PWSTR` that points to a non-null-terminated string, breaking its contract.

Maybe a short term fix would be to pick up on `[NotNullTerminated]` annotated `PWSTR`s and replace them with `*mut _`.

On the metadata side, perhaps we can then extend the `[NotNullTerminated]` attribute to include a parameter that indicates which field member can be relied upon for the string length. (Or just re-use `[NativeArrayInfo]` or `[MemorySize]`, it's not clear yet.) This should aid codegen in determining whether to provide a nicer facility or to emit the raw pointer.

Some other APIs and structures that make use of non-null-terminated `PWSTR`s (from metadata's perspective) that we need to keep in mind:
* [USB_ID_STRING](https://learn.microsoft.com/windows-hardware/drivers/ddi/usbioctl/ns-usbioctl-_usb_id_string)
* [TRUSTEE_W](https://learn.microsoft.com/windows/win32/api/accctrl/ns-accctrl-trustee_w)
* [HTTP_SERVICE_BINDING_W](https://learn.microsoft.com/windows/win32/api/http/ns-http-http_service_binding_w)
* [DsUnquoteRdnValueW](https://learn.microsoft.com/windows/win32/api/dsparse/nf-dsparse-dsunquoterdnvaluew)
* [SetEnvironmentStringsW](https://learn.microsoft.com/windows/win32/api/processenv/nf-processenv-setenvironmentstringsw)

**Comment by tim-weis** [comment] 2023-07-17 14:45
[`SetEnvironmentStringsW`](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-setenvironmentstringsw) (and friends) are interesting in a number of ways:

1. The SDK header file *processenv.h* describes the argument using the `_NullNull_terminated_` annotation. Ignoring the [misnomer](https://devblogs.microsoft.com/oldnewthing/20091008-00/?p=16443) this is roughly correct.
2. The function signature in the metadata looks like this:
   ```csharp
   BOOL SetEnvironmentStringsW([In][NotNullTerminated][NullNullTerminated] PWSTR NewEnvironment);
   ```

It's the metadata transformation that uncovers a few issues with the current approach. The obvious one up front: `[NotNullTerminated]` AND `[NullNullTerminated]` creates a conflict that cannot be resolved. One could argue that `[NotNullTerminated]` is to only mean *"might not be null-terminated"*, but really, things are wrong at a much more fundamental level.

Specifically, the implied assumption that `PWSTR` is null-terminated, but without a dedicated `[NullTerminated]` attribute, introduced the need for the awkward negative attribute `[NotNullTerminated]` for the `PWCH` type.

A more tractable scheme would be as follows:

* Treat `PWCH` as the **unconstrained** character pointer type, and expose it.
* Use the `[NullTerminated]` attribute for all `PWSTR`s.
* Introduce the `[NullNullTerminated]` attribute, expose the `PZZWSTR` type with that attribute, or pick up the attribute where it happens to be spelled out in the function signature (e.g. `SetEnvironmentStringsW`).
* Treat all attributes as strictly additive.

With those changes the transformed signature would look like this:

```csharp
BOOL SetEnvironmentStringsW([In][NullNullTerminated] PWCH NewEnvironment);
```

Are there any issues with this proposed change, and would the win32metadata team be willing to act upon it (assuming that riddle isn't going to make *Windows.Win32.winmd* obsolete at some point)?

**Comment by kennykerr** [comment] 2023-07-17 15:38
Yep there are a lot of issues with the Win32 metadata, hence my previous comment on focus https://github.com/microsoft/windows-rs/issues/2566#issuecomment-1634375903 rather than short term workarounds for issues like this that are not blocking.

**Comment by riverar** [comment] 2023-07-20 17:39
Kenny is currently heads down working on _riddle_ to simplify WinRT and Win32 component authoring and code generation. We are actively exploring other potential areas where _riddle_ could be used but we there's nothing to share yet. (Literally. I'm not trying to be evasive.)

Regarding contributions to the metadata repositories: I'd say yes, please do continue. Anything done in those repositories will certainly serve as a baseline for any potential future work and benefits all projections, not just Rust.

**Comment by kennykerr** [comment] 2023-07-21 14:51
@tim-weis I hope to share more about those plans as soon as I can. Thanks for your patience.

**Comment by kennykerr** [comment] 2023-09-06 18:14
There's not much more I can do at this time. Feel free to keep chatting and we can reopen when there's actionable work to be done.

**Closed by kennykerr** 2023-09-06 18:14 UTC
Labels: question
