### ISSUE TITLE
2 tests fails due problem with translations

### ISSUE THREAD

**Issue by qarmin** [microsoft/windows-rs#970] opened 2021-07-10 11:47 UTC
When I run `cargo test`, then 2 tests fails with this info
```
running 14 tests
test result::error::tests::win32_error_conversion ... ok
test result::hresult::tests::test_message ... FAILED
test runtime::array::tests::empty ... ok
test result::error::tests::test_message ... FAILED
test runtime::array::tests::with_len ... ok
test runtime::guid::tests::test_new ... ok
test runtime::hstring::tests::abi_transfer ... ok
test runtime::hstring::tests::debug_format ... ok
test runtime::hstring::tests::display_format ... ok
test runtime::hstring::tests::from_empty_string ... ok
test runtime::hstring::tests::hstring_to_string ... ok
test runtime::hstring::tests::hstring_to_string_err ... ok
test runtime::hstring::tests::hstring_to_string_lossy ... ok
test runtime::hstring::tests::hstring_works ... ok

failures:

---- result::hresult::tests::test_message stdout ----
thread 'result::hresult::tests::test_message' panicked at 'assertion failed: `(left == right)`
  left: `"Operacja ukończona pomyślnie."`,
 right: `"The operation completed successfully."`', src\result\hresult.rs:160:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- result::error::tests::test_message stdout ----
thread 'result::error::tests::test_message' panicked at 'assertion failed: `(left == right)`
  left: `"Operacja ukończona pomyślnie."`,
 right: `"The operation completed successfully."`', src\result\error.rs:174:9


failures:
    result::error::tests::test_message
    result::hresult::tests::test_message

test result: FAILED. 12 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```
I used Windows Server 2019 with Polish language and Rust 1.53

**Comment by kennykerr** [comment] 2021-07-10 14:52
Duplicate of #808

**Closed by kennykerr** 2021-07-10 14:52 UTC
