### ISSUE TITLE
The Constructor Pattern for Windows API structures

### ISSUE THREAD

**Issue by SonyStone** [microsoft/windows-rs#1028] opened 2021-08-10 15:32 UTC
Hi everyone. 👋
I have a question: 
Are there any plans to extend the generator to create сonstructor methods for structures?
For example, there is a structure WNDCLASSW.
Instead of writing as in the [example](https://github.com/microsoft/windows-samples-rs/blob/master/create_window/src/main.rs#L15):
```rust
let wc = WNDCLASSA {
            hCursor: LoadCursorW(None, IDC_ARROW),
            hInstance: instance,
            lpszClassName: PSTR(b"window\0".as_ptr() as _),
            style: CS_HREDRAW | CS_VREDRAW,
            lpfnWndProc: Some(wndproc),
            ..Default::default()
        };
```

Make it so that you can write something like this:

```rust
let wc = WNDCLASSW::default()
        .hCursor(LoadCursorW(None, IDC_ARROW))
        .lpfnWndProc(wndproc)
        .lpszClassName(window)
        .hInstance(instance)
        .style(CS_HREDRAW | CS_VREDRAW);
```

**Comment by kennykerr** [comment] 2021-08-12 04:57
Good idea, I'm not sure whether to roll out the builder/constructor pattern more broadly yet. For example, the `lpszClassName` field has ownership issues. It would be simpler to support in WinRT. Duplicate of #153.

**Comment by SonyStone** [comment] 2021-08-13 06:55
What's the issue with ownership?
I made and used this trait, there seemed to be no problems.
```rust
// Builder pattern?
#[allow(non_snake_case)]
trait SetWNDCLASSW<'a> {
    fn lpszClassName(self, lpszClassName: impl IntoParam<'a, PWSTR>) -> Self;
    fn style(self, style: WNDCLASS_STYLES) -> Self;
    fn lpfnWndProc(self, lpfnWndProc: WNDPROC) -> Self;
    fn hInstance(self, hInstance: impl IntoParam<'a, HINSTANCE>) -> Self;
    fn hCursor(self, hCursor: impl IntoParam<'a, HCURSOR>) -> Self;
}

#[allow(non_snake_case)]
impl<'a> SetWNDCLASSW<'a> for WNDCLASSW {
    fn lpszClassName(mut self, lpszClassName: impl IntoParam<'a, PWSTR>) -> Self {
        self.lpszClassName = lpszClassName.into_param().abi();
        self
    }
    fn style(mut self, style: WNDCLASS_STYLES) -> Self {
        self.style = style;
        self
    }
    fn lpfnWndProc(mut self, window_procedure_dispatch: WNDPROC) -> Self {
        self.lpfnWndProc = Some(window_procedure_dispatch);
        self
    }
    fn hInstance(mut self, hInstance: impl IntoParam<'a, HINSTANCE>) -> Self {
        self.hInstance = hInstance.into_param().abi();
        self
    }
    fn hCursor(mut self, hCursor: impl IntoParam<'a, HCURSOR>) -> Self {
        self.hCursor = hCursor.into_param().abi();
        self
    }
}
```

**Comment by SonyStone** [comment] 2021-09-01 01:02
I still don't understand, the value `IntoParam<'a, PWSTR>` have lifetime parameter. Shouldn't it prevent it from this issue?

**Comment by kennykerr** [comment] 2021-09-01 03:37
It's called `IntoParam` because it works for the lifetime of a synchronous function call and its associated parameters. The resulting `Param` (returned by the `into_param` function) is stack-allocated and can happily consume more stack space to accommodate the borrowed/copied value. The `abi` function is grabbing a reference to that stack value, so your example above is invalid as the stack will be vacated by the time the structure is used. 

I'm going to reopen this issue as that lifetime parameter is misleading and the code you wrote should not compile. At the very least, the `abi` call should be unsafe.

**Comment by MarijnS95** [comment] 2021-09-01 08:35
Note that loosing this lifetime isn't considered unsafe - dereferencing a raw pointer is. Look at the various `as_(mut_)ptr()` examples in the standard library; none is marked unsafe while they return a raw pointer. With structs it does make for API that's easy to break though, which might make it interesting to provide such a safe constructor pattern where the functions borrow and capture a `Param` (for example) in its lifetime.

**Comment by kennykerr** [comment] 2021-09-01 16:50
Yep, in this case it is not safe regardless of whether `Param` holds a copy or reference.

**Closed** 2021-09-01 17:42 UTC
Labels: bug
