### ISSUE TITLE
Bug: IXAudio2MasteringVoice and IXAudio2SourceVoice do not have GUID.

### ISSUE THREAD

**Issue by binarray** [microsoft/windows-rs#1903] opened 2022-07-13 03:47 UTC
### Which crate is this about?

windows

### Crate version

3.80

### Summary

IXAudio2MasteringVoice and IXAudio2SourceVoice do not have GUID.
 
When the lifetime of these objects ends, calling IUnknown.vtable().Release will result in an "Access violation reading location" exception.

I used rust's std::mem::forget to disable the destructor to get around this. Is there a better solution?

**Comment by kennykerr** [comment] 2022-07-13 03:59
> IXAudio2MasteringVoice and IXAudio2SourceVoice do not have GUID.

That's true but looking at the headers in the Windows SDK those interfaces don't appear to have GUIDs associated with them either. The `windows` crate simply reflects the APIs as they are defined in the Windows SDK. 

> When the lifetime of these objects ends, calling IUnknown.vtable().Release will result in an "Access violation reading location" exception.

This sounds like an unrelated problem, typically due to incorrect COM calling on the client side. There are a few good COM-related samples here:

https://github.com/microsoft/windows-rs/tree/master/crates/samples

If you believe there's a bug with the `windows` crate, please share a minimal repro. Otherwise, for general API questions I suggest [stackoverflow.com](https://stackoverflow.com/) or https://docs.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by binarray** [comment] 2022-07-13 04:31
This is the same issue:
https://docs.microsoft.com/en-us/answers/questions/134045/ixaudio2masteringvoice-error-when-enclosed-in-a-co.html

If we can't call release method in IXAudio2MasteringVoice, why does it implement a drop function with release inside?
Is this really not a bug?

I think remove the drop function in the  IXAudio2MasteringVoice is a solution.

**Comment by kennykerr** [comment] 2022-07-13 04:35
Oh, I see that these interfaces don't actually derive from `IUnknown` - that's the real issue here. They are not COM interfaces at all. I will have to deal with that.

**Comment by kennykerr** [comment] 2022-07-13 05:12
Duplicate of #453 - good reminder to get that working somehow.

**Closed by kennykerr** 2022-07-13 05:12 UTC
Labels: question
