### ISSUE TITLE
No longer able to work with VARIANT

### ISSUE THREAD

**Issue by hcldan** [microsoft/windows-rs#2884] opened 2024-02-26 18:02 UTC
### Summary

The 0.53.0 update provided some "improved" handling for VARIANT structs.

This change removed the ability to inspect the details of the VARIANT, making some of the use-cases I am using impossible.

I realize that you want a rust-safe way to deal with things in this crate, but I need way more control that what I am given. I need to be able to create variants of arbitrary type, from their underlying data representations.

I used to be able to do this.

While I think it's great that you guys are working on improving the rust binding support...  I don't think that the C bindings should be hidden. You are effectively making rust a second-class citizen by hiding a bunch of stuff C programs have access to.

Instead of using VARIANT everywhere in the rust crate... why don't you make a `RustVariant` type instead that the new apis use, so that it's still possible to do lower-level stuff.

**Comment by hcldan** [comment] 2024-02-26 18:28
One example of the fallout here is: #2877.

**Comment by hcldan** [comment] 2024-02-26 18:29
> I think all that you would need to do is make a
> 
> ```rust
> inner(self) -> imp::VARIANT;
> ```
> 
> impl for `VARIANT` so that I could continue my work.
> 
> Or implement `From<VARIANT> for imp::VARIANT` and the reverse.

If you go this route, I would need to understand what to do for making sure memory is safe.
I was looking through imp::VARIANT* and it looks like the `ManuallyDrop`s are gone?

**Comment by kennykerr** [comment] 2024-02-26 20:16
Let's keep the conversation in one place. Closing as duplicate of #2877.

**Closed by kennykerr** 2024-02-26 20:16 UTC
Labels: bug

**Comment by hcldan** [comment] 2024-02-26 21:15
@kennykerr I would ask that you re-open this. Supporting more types is not really the problem this issue is addressing.  Unless you want to add imp::VARIANT conversion to VARIANT in the other issue.

**Comment by kennykerr** [comment] 2024-02-26 22:53
I'd rather just discuss all issues/requests for VARIANT related support in one place.
