### ISSUE TITLE
Not for CONSOLE_MODE?

### ISSUE THREAD

**Issue by ibigbug** [microsoft/windows-rs#1132] opened 2021-09-14 15:05 UTC
Can I do bitwise not for [CONSOLE_MODE](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Console/struct.CONSOLE_MODE.html)?

```
            if !SetConsoleMode(
                h_console,
                console_mode | !ENABLE_VIRTUAL_TERMINAL_PROCESSING,
            )
```

this piece of code doesn't compile:

```
error[E0600]: cannot apply unary operator `!` to type `Console::CONSOLE_MODE`
   --> terminal\src\windows\terminal.rs:109:32
    |
109 |                 console_mode | !ENABLE_VIRTUAL_TERMINAL_PROCESSING,
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot apply unary operator `!`
    |
    = note: an implementation of `std::ops::Not` might be missing for `Console::CONSOLE_MODE`

For more information about this error, try `rustc --explain E0600`.
error: could not compile `terminal` due to previous error
```

Seems CONSOLE_MODE only implemented `BitAnd` and `BitOr`, but `use std::ops::Not;` was not implemented.

Is there anything that I missed?

**Comment by kennykerr** [comment] 2021-09-14 16:33
Looks like this is a duplicate of #696

**Closed** 2021-09-14 19:35 UTC
Labels: enhancement

**Comment by riverar** [comment] 2021-09-14 19:37
@ibigbug This is now supported in latest master. Let us know if you run into any issues.

**Comment by ibigbug** [comment] 2021-09-15 07:56
thanks @riverar , working perfect!
