### ISSUE TITLE
[Question] Generating interfaces from existing winmd/idl

### ISSUE THREAD

**Issue by chuckries** [microsoft/windows-rs#1859] opened 2022-06-30 18:01 UTC
Since the last time I looked into windows-rs, it appears the project has changed from shipping a winmd reader and generating bindings at build time to shipping a set of pregenerated bindings. In old, build time generation mode it was possible to provide additional winmd's and generate bindings for user defined WinRT API's that were not represented in the Win32 Metadata Project.

Is there any supported way to generate bindings in addition to what is shipped in the existing crates? 

In addition, I am interested in using rust to interface with more classic COM apis for which there may be IDL or native headers for, but not a winmd. Is there any supported way to generate bindings for apis such as these?

**Comment by riverar** [comment] 2022-06-30 20:04
Hey @chuckries,

We just had a similar request come in few days ago, see #1856 for more details and a quick sample. Official documentation is still pending.

Closing as duplicate of #1856, #1518. Feel free to continue the discussion!

**Closed by riverar** 2022-06-30 20:04 UTC
Labels: question

**Comment by kennykerr** [comment] 2022-06-30 20:05
Yep, the `windows-metadata` and `windows-bindgen` crates now provide library support for what the old `build` macro provided.
