### ISSUE TITLE
FILE_GENERIC_READ not found in metadata

### ISSUE THREAD

**Issue by 74wny0wl** [microsoft/windows-rs#893] opened 2021-06-22 03:51 UTC
I can't use [FILE_GENERIC_READ](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Storage/FileSystem/constant.FILE_GENERIC_READ.html)

On windows v0.11.0, after ```cargo build```, there is an error:

```
error: `Windows.Win32.Storage.FileSystem.FILE_GENERIC_READ` not found in metadata
 --> bindings\build.rs:8:46
  |
8 |         Windows::Win32::Storage::FileSystem::FILE_GENERIC_READ,
  |                                              ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `bindings`
```

I've checked used ```windows``` versions:

```
PS C:\Users\74wny0wl\sample-tool> cargo tree | sls windows

Γöé   ΓööΓöÇΓöÇ windows v0.11.0
Γöé       Γö£ΓöÇΓöÇ windows_gen v0.11.0
Γöé       ΓööΓöÇΓöÇ windows_macros v0.11.0 (proc-macro)
Γöé           ΓööΓöÇΓöÇ windows_gen v0.11.0
Γöé   ΓööΓöÇΓöÇ windows v0.11.0 (*)
ΓööΓöÇΓöÇ windows v0.11.0 (*)
```

My ```bindings\build.rs``` file:
```
fn main() {
    windows::build!(
       //...
        Windows::Win32::Storage::FileSystem::FILE_GENERIC_READ,
       //...
  )
}

```

**Comment by tim-weis** [comment] 2021-06-22 07:25
This looks like a duplicate of #871. The solution here is to use the following `build.rs` script:

```rust
fn main() {
    windows::build!(Windows::Win32::Storage::FileSystem::FILE_ACCESS_FLAGS)
}
```

This generates the `FILE_GENERIC_READ` constant into `bindings::Windows::Win32::Storage::FileSystem`, and it can be brought into scope with this statement:

```rust
use bindings::Windows::Win32::Storage::FileSystem::FILE_GENERIC_READ;
```

**Comment by 74wny0wl** [comment] 2021-06-22 18:05
OK, this solution is working now, thanks!
Is it workaround or is it the correct way to use bindings now?

**Comment by tim-weis** [comment] 2021-06-22 18:24
It was a judicious decision (PR: #843, linked issue: #831). You're probably going to start appreciating this change by the time you use the second constant of a particular type. It's immediately available without requiring an update to the *build.rs* script.

**Closed** 2021-06-22 19:51 UTC
Labels: question
