### ISSUE TITLE
Documentation for older versions

### ISSUE THREAD

**Issue by ydirson** [microsoft/windows-rs#2750] opened 2023-12-21 15:03 UTC
### Suggestion

The Rust ecosystem is such that you don't always have the choice to use latest version: crate `wmi` still uses 0.48, so I'm stuck with that old version to be able to exchange `windows` objects with it, but https://microsoft.github.io/windows-docs-rs/ does not give the option to get anything else than 0.52.  `docs.rs` OTOH is great at keeping old docs, for example.

**Comment by kennykerr** [comment] 2023-12-21 20:51
Unfortunately, there's no way to support that on `windows-docs-rs` and `docs.rs` can't handle the `windows` crate otherwise I'd just use that.

**Comment by ydirson** [comment] 2023-12-22 11:01
Note sure what the problem is, but as a workaround maybe the built does could be made available for download somewhere?

**Comment by tim-weis** [comment] 2023-12-22 14:30
@ydirson The workaround is to generate the documentation on your local machine by running `cargo doc`.

**Comment by kennykerr** [comment] 2023-12-22 15:20
The problem is that the docs generated by `cargo doc` are massive and exceed the limits imposed by `docs.rs` for generation and hosting. #2717 is tracking alternatives so I'll close this.

**Comment by Enyium** [comment] 2023-12-22 15:21
With a huge crate like the `windows` crate that, to make matters worse, regularly publishes breaking releases that make unchanged types incompatible with themselves from earlier version, there really is a special approach needed when a crate wants to allow its users to seamlessly use it together with the `windows` crate's types.

In `windows-helpers` (work in progress; [`Cargo.toml`](https://github.com/Enyium/windows-helpers-rs/blob/master/Cargo.toml)), I established features like `windows_v0_48`, so the user can make the crate work with an older `windows` crate version (most things in `windows` don't change anyway, or not in a hard to support way).

I'm thinking whether a part of the Rust ecosystem wouldn't benefit from formalizing an approach similar to this, or providing better, DRYer means to accomplish it.

**Closed by kennykerr** 2023-12-22 15:20 UTC
Labels: question
