### ISSUE TITLE
Bug: Conversion from `windows::core::Error` to `std::io::Error` is wrong

### ISSUE THREAD

**Issue by mbartlett21** [microsoft/windows-rs#1839] opened 2022-06-22 02:38 UTC
### Which crate is this about?

windows

### Crate version

0.37.0

### Summary

The conversion from `windows::core::Error` to `std::io::Error` changes the error.

For example:

This:
```
[src\main.rs:333] s.picker.PickSingleFolderAsync() = Err(
    Error {
        code: 0x80004005,
        message: The FileTypeFilters property must have at least one file type filter specified.,
    },
)
```

Gets turned into this:

(yes, it is the display, not debug shown here, but the error type is the point)
```
OS Error 16389 (FormatMessageW() returned error 317) (os error 16389)
```

https://github.com/microsoft/windows-rs/blob/6a3a7489e3122dc4e7f51605e05f4061769e895d/crates/libs/windows/src/core/error.rs#L78-L82

### Reproducible example

```rust
// TODO

// Basically use a file picker without setting the FileTypeFilter to get the result

// Then convert the error to io::Error using io::Error::from
```

### Expected behavior

The error codes and descriptions are the same

**Comment by riverar** [comment] 2022-06-22 03:15
Duplicate of #1807 fixed in #1809 👍

**Closed by riverar** 2022-06-22 03:15 UTC
Labels: bug
