### ISSUE TITLE
Using windows-rs with #![no_std]

### ISSUE THREAD

**Issue by tathanhdinh** [microsoft/windows-rs#505] opened 2021-02-03 09:43 UTC
Hello,
How can I use windows-rs with ``#![no_std]`? 

I've created a simple test with `main.rs` like that:

```rust
#![no_std]
#![no_main]
#![feature(asm)]
#![windows_subsystem = "console"]

mod bindings {
    ::windows::include_bindings!();
}

use bindings::{
    windows::win32::system_services::CreateThread
};

#[no_mangle]
unsafe extern "C" fn mainCRTStartup() {}

#[panic_handler]
fn custom_panic(_info: &'_ core::panic::PanicInfo) -> ! {
    loop {}
}
```

while `build.rs`:

```rust
fn main() {
    windows::build!(
        windows::win32::system_services::{CreateThread, Sleep}
        windows::win32::windows_programming::CloseHandle
    );
}
```

and `.cargo/config`:

```
[build]
rustflags = ["-C", "link-args=/DEBUG:NONE /PDBALTPATH:%_PDB% /ENTRY:mainCRTStartup", "-C", "target-feature=+crt-static"]
```

but `cargo build` reports some errors about creation of `windows_winmd_macros-....dll`.

**Comment by rylev** [comment] 2021-02-03 10:51
The `windows` crate does not support `#[no_std]` currently, but it should be able to. We just need to add that functionality.

**Comment by kennykerr** [comment] 2021-02-19 17:37
Duplicate of #427.

**Comment by kennykerr** [comment] 2021-02-19 17:37
Duplicate of #427

**Closed** 2021-02-19 17:38 UTC
Labels: enhancement
