### ISSUE TITLE
Win32 Application Specific Audio Loopback

### ISSUE THREAD

**Issue by JohnMitchell04** [microsoft/windows-rs#2995] opened 2024-04-15 18:04 UTC
### Suggestion

First of all, many thanks to the maintainers of this crate and apologies as this is a question but I cannot mark as such. I also apologise if this is obvious, I am relatively new to rust and windows API programming.

I am attempting to implement application specific audio loopback and capture as detailed in this [Win32 sample](https://learn.microsoft.com/en-us/samples/microsoft/windows-classic-samples/applicationloopbackaudio-sample/) - all of the important stuff is in LoopbackCapture.cpp. I have also been leaning on the OBS github as they have a more robust application as detailed in [this file](https://github.com/obsproject/obs-studio/blob/master/plugins/win-wasapi/win-wasapi.cpp) - all of the important stuff is line 711 onwards.

My current rust code seems to succeed (there are no errors) however the returned audio samples are all 0 (silence). I can successfully run both the Win32 sample and OBS repository and both successfully capture audio. I have also modified the Win32 sample to accept a float based format, different from the hardcoded one provided and that is also successful. So I can successfully do what I want in C++, however I cannot in Rust.

I was wondering if anyone could provide some help, my code will be provided below with some parts removed for brevity.

```Rust
// Completion Handler defined here //

fn main() {
    // Get process id

    // Initialize COM
    unsafe {
        let result = CoInitializeEx(None, COINIT_APARTMENTTHREADED);
        result.unwrap();
    };

    // Set desired activation parameters
    let audio_client_activation_params = AUDIOCLIENT_ACTIVATION_PARAMS {
        ActivationType: AUDIOCLIENT_ACTIVATION_TYPE_PROCESS_LOOPBACK,
        Anonymous: AUDIOCLIENT_ACTIVATION_PARAMS_0 {
            ProcessLoopbackParams: AUDIOCLIENT_PROCESS_LOOPBACK_PARAMS {
                TargetProcessId: process_id,
                ProcessLoopbackMode: PROCESS_LOOPBACK_MODE_INCLUDE_TARGET_PROCESS_TREE,
            },
        },
    };

    // Create PROPVARIANT for the audio client activation params
    let raw_prop = windows_core::imp::PROPVARIANT {
        Anonymous: windows_core::imp::PROPVARIANT_0 {
            Anonymous: windows_core::imp::PROPVARIANT_0_0 {
                vt: VT_BLOB.0,
                wReserved1: 0,
                wReserved2: 0,
                wReserved3: 0,
                Anonymous: windows_core::imp::PROPVARIANT_0_0_0 {
                    blob: windows_core::imp::BLOB {
                        cbSize: size_of::<AUDIOCLIENT_ACTIVATION_PARAMS>() as u32,
                        pBlobData: &audio_client_activation_params as *const _ as *mut _,
                    }
                }
            },
        },
    };
    let activation_prop: PROPVARIANT;
    unsafe { activation_prop =  PROPVARIANT::from_raw(raw_prop); };
    let activation_params = Some(&activation_prop as *const _);

    // Get audio client GUID
    let riid = IAudioClient::IID;

    // Create completion handler
    let setup = Arc::new((Mutex::new(false), Condvar::new()));
    let callback: IActivateAudioInterfaceCompletionHandler = Handler::new(setup.clone()).into();

    // Activate audio interface
    let operation: IActivateAudioInterfaceAsyncOperation;
    unsafe {
        operation = ActivateAudioInterfaceAsync(
            VIRTUAL_AUDIO_DEVICE_PROCESS_LOOPBACK,
            &riid, 
            activation_params, 
            &callback
        ).unwrap();
    };

    // Wait for completion
    let (lock, cvar) = &*setup;
    let mut completed = lock.lock().unwrap();
    while !*completed {
        completed = cvar.wait(completed).unwrap();
    }
    drop(completed);

    // Get audio client and result
    let mut audio_client: Option<IUnknown> = Default::default();
    let mut result: HRESULT = Default::default();
    unsafe { operation.GetActivateResult(&mut result, &mut audio_client).unwrap(); };

    // Ensure successful activation
    result.unwrap();
    let audio_client: IAudioClient = audio_client.unwrap().cast().unwrap();

    // Audio client arguments
    let block_align = 2 * 32 / 8;
    let byte_rate = 44100 * block_align;

    let extensible = WAVEFORMATEXTENSIBLE {
        Format: WAVEFORMATEX {
            wFormatTag: WAVE_FORMAT_EXTENSIBLE as u16,
            nChannels: 2,
            nSamplesPerSec: 48000,
            nAvgBytesPerSec: byte_rate,
            nBlockAlign: block_align as u16,
            wBitsPerSample: 32,
            cbSize: (size_of::<WAVEFORMATEXTENSIBLE>() - size_of::<WAVEFORMATEX>()) as u16
        },
        Samples: WAVEFORMATEXTENSIBLE_0 { wValidBitsPerSample: 32 },
        SubFormat: KSDATAFORMAT_SUBTYPE_IEEE_FLOAT,
        dwChannelMask: 0x1 | 0x2,
    };

    let stream_flags = AUDCLNT_STREAMFLAGS_EVENTCALLBACK | AUDCLNT_STREAMFLAGS_LOOPBACK;

    // Initialise audio client
    unsafe { audio_client.Initialize(AUDCLNT_SHAREMODE_SHARED, stream_flags, 200000, 0, &extensible.Format, None).unwrap(); };

    // Get capture client
    let capture_client;
    unsafe { capture_client = audio_client.GetService::<IAudioCaptureClient>().unwrap(); };

    // Set event handle
    let h_event;
    unsafe {
        h_event = CreateEventA(None, false, false, PCSTR::null()).unwrap();
        audio_client.SetEventHandle(h_event).unwrap();
    };

    unsafe { audio_client.Start().unwrap(); };

    println!("Starting main loop");

    // Main loop
    loop {
        // Get pointer to buffer
        let mut buffer_ptr = ptr::null_mut();
        let mut nbr_frames_returned = 0;
        let mut flags = 0;
        unsafe { capture_client.GetBuffer(&mut buffer_ptr, &mut nbr_frames_returned, &mut flags, None, None).unwrap(); };

        // Fill buffer
        let len_in_bytes = nbr_frames_returned as usize * block_align as usize;
        let bufferslice;
        unsafe { bufferslice = slice::from_raw_parts(buffer_ptr, len_in_bytes); };
        
        // Look for a non silent sample
        let mut non_zero = false;
        for element in bufferslice.iter() {
            if *element != 0 {
                non_zero = true;
            }
        }

        if non_zero {
            println!("Non-zero sample found");
        }

        // Release buffer
        if nbr_frames_returned > 0 {
            unsafe { capture_client.ReleaseBuffer(nbr_frames_returned).unwrap(); }; 
        }

        // Read from device to queue
        let retval;
        unsafe { retval = WaitForSingleObject(h_event, 100000); };
        if retval.0 != WAIT_OBJECT_0.0 {
            panic!("AHHHHH");
        }
    }
}
```

Many thanks, any help is appreciated.

**Comment by riverar** [comment] 2024-04-15 23:19
After re-implementing the missing parts of the provided repro., and correcting the sampling rate and loop along the way, I ended up with this:

```rust
use std::{
    mem::size_of,
    ptr, slice,
    sync::{Arc, Condvar, Mutex},
};

use windows::{
    core::{implement, IUnknown, Interface, HRESULT, PCSTR, PROPVARIANT},
    Win32::{
        Foundation::WAIT_OBJECT_0,
        Media::{
            Audio::{
                ActivateAudioInterfaceAsync, IActivateAudioInterfaceAsyncOperation,
                IActivateAudioInterfaceCompletionHandler,
                IActivateAudioInterfaceCompletionHandler_Impl, IAudioCaptureClient, IAudioClient,
                AUDCLNT_SHAREMODE_SHARED, AUDCLNT_STREAMFLAGS_EVENTCALLBACK,
                AUDCLNT_STREAMFLAGS_LOOPBACK, AUDIOCLIENT_ACTIVATION_PARAMS,
                AUDIOCLIENT_ACTIVATION_PARAMS_0, AUDIOCLIENT_ACTIVATION_TYPE_PROCESS_LOOPBACK,
                AUDIOCLIENT_PROCESS_LOOPBACK_PARAMS,
                PROCESS_LOOPBACK_MODE_INCLUDE_TARGET_PROCESS_TREE,
                VIRTUAL_AUDIO_DEVICE_PROCESS_LOOPBACK, WAVEFORMATEX, WAVEFORMATEXTENSIBLE,
                WAVEFORMATEXTENSIBLE_0,
            },
            KernelStreaming::WAVE_FORMAT_EXTENSIBLE,
            Multimedia::KSDATAFORMAT_SUBTYPE_IEEE_FLOAT,
        },
        System::{
            Com::{CoInitializeEx, COINIT_APARTMENTTHREADED},
            Threading::{CreateEventA, WaitForSingleObject},
            Variant::VT_BLOB,
        },
    },
};

#[implement(IActivateAudioInterfaceCompletionHandler)]
struct Handler(Arc<(Mutex<bool>, Condvar)>);

impl Handler {
    pub fn new(object: Arc<(Mutex<bool>, Condvar)>) -> Handler {
        Handler(object)
    }
}

impl IActivateAudioInterfaceCompletionHandler_Impl for Handler {
    fn ActivateCompleted(
        &self,
        _activateoperation: Option<&IActivateAudioInterfaceAsyncOperation>,
    ) -> windows::core::Result<()> {
        let (lock, cvar) = &*self.0;
        let mut completed = lock.lock().unwrap();
        *completed = true;
        drop(completed);
        cvar.notify_one();
        Ok(())
    }
}

fn main() -> windows::core::Result<()> {
    let process_id = 239160;

    unsafe {
        // Initialize COM
        CoInitializeEx(None, COINIT_APARTMENTTHREADED).ok()?;

        // Create audio client
        let audio_client_activation_params = AUDIOCLIENT_ACTIVATION_PARAMS {
            ActivationType: AUDIOCLIENT_ACTIVATION_TYPE_PROCESS_LOOPBACK,
            Anonymous: AUDIOCLIENT_ACTIVATION_PARAMS_0 {
                ProcessLoopbackParams: AUDIOCLIENT_PROCESS_LOOPBACK_PARAMS {
                    TargetProcessId: process_id,
                    ProcessLoopbackMode: PROCESS_LOOPBACK_MODE_INCLUDE_TARGET_PROCESS_TREE,
                },
            },
        };

        let raw_prop = windows_core::imp::PROPVARIANT {
            Anonymous: windows_core::imp::PROPVARIANT_0 {
                Anonymous: windows_core::imp::PROPVARIANT_0_0 {
                    vt: VT_BLOB.0,
                    wReserved1: 0,
                    wReserved2: 0,
                    wReserved3: 0,
                    Anonymous: windows_core::imp::PROPVARIANT_0_0_0 {
                        blob: windows_core::imp::BLOB {
                            cbSize: size_of::<AUDIOCLIENT_ACTIVATION_PARAMS>() as u32,
                            pBlobData: &audio_client_activation_params as *const _ as *mut _,
                        },
                    },
                },
            },
        };

        let activation_prop = PROPVARIANT::from_raw(raw_prop);
        let activation_params = Some(&activation_prop as *const _);
        let riid = IAudioClient::IID;

        // Create completion handler
        let setup = Arc::new((Mutex::new(false), Condvar::new()));
        let callback: IActivateAudioInterfaceCompletionHandler = Handler::new(setup.clone()).into();

        // Activate audio interface
        let operation = ActivateAudioInterfaceAsync(
            VIRTUAL_AUDIO_DEVICE_PROCESS_LOOPBACK,
            &riid,
            activation_params,
            &callback,
        )?;

        // Wait for completion
        let (lock, cvar) = &*setup;
        let mut completed = lock.lock().unwrap();
        while !*completed {
            completed = cvar.wait(completed).unwrap();
        }
        drop(completed);

        // Get audio client and result
        let mut audio_client: Option<IUnknown> = Default::default();
        let mut result: HRESULT = Default::default();
        operation.GetActivateResult(&mut result, &mut audio_client)?;

        // Ensure successful activation
        result.ok()?;
        let audio_client: IAudioClient = audio_client.unwrap().cast()?;

        // Audio client arguments
        let block_align = 2 * 32 / 8;
        let byte_rate = 44100 * block_align;

        let extensible = WAVEFORMATEXTENSIBLE {
            Format: WAVEFORMATEX {
                wFormatTag: WAVE_FORMAT_EXTENSIBLE as u16,
                nChannels: 2,
                nSamplesPerSec: 44100,
                nAvgBytesPerSec: byte_rate,
                nBlockAlign: block_align as u16,
                wBitsPerSample: 32,
                cbSize: (size_of::<WAVEFORMATEXTENSIBLE>() - size_of::<WAVEFORMATEX>()) as u16,
            },
            Samples: WAVEFORMATEXTENSIBLE_0 {
                wValidBitsPerSample: 32,
            },
            SubFormat: KSDATAFORMAT_SUBTYPE_IEEE_FLOAT,
            dwChannelMask: 0x1 | 0x2,
        };

        let stream_flags = AUDCLNT_STREAMFLAGS_EVENTCALLBACK | AUDCLNT_STREAMFLAGS_LOOPBACK;

        // Initialise audio client
        audio_client.Initialize(
            AUDCLNT_SHAREMODE_SHARED,
            stream_flags,
            200000,
            0,
            &extensible.Format,
            None,
        )?;

        // Get capture client
        let capture_client = audio_client.GetService::<IAudioCaptureClient>()?;

        // Set event handle
        let h_event = CreateEventA(None, false, false, PCSTR::null())?;
        audio_client.SetEventHandle(h_event)?;
        audio_client.Start()?;

        println!("Starting main loop");

        // Main loop
        loop {
            let frames_available = capture_client.GetNextPacketSize()?;
            if frames_available < 1 {
                continue;
            }

            // Get pointer to buffer
            let mut buffer_ptr = ptr::null_mut();
            let mut nbr_frames_returned = 0;
            let mut flags = 0;
            capture_client.GetBuffer(
                &mut buffer_ptr,
                &mut nbr_frames_returned,
                &mut flags,
                None,
                None,
            )?;

            // Fill buffer
            let len_in_bytes = nbr_frames_returned as usize * block_align as usize;
            let bufferslice = slice::from_raw_parts(buffer_ptr, len_in_bytes);

            // Look for a non silent sample
            let mut non_zero = false;
            for element in bufferslice.iter() {
                if *element != 0 {
                    non_zero = true;
                }
            }

            if non_zero {
                println!("Non-zero sample found");
            }

            // Release buffer
            if nbr_frames_returned > 0 {
                capture_client.ReleaseBuffer(nbr_frames_returned).unwrap();
            }

            // Read from device to queue
            let retval = WaitForSingleObject(h_event, 100000);
            if retval.0 != WAIT_OBJECT_0.0 {
                panic!("AHHHHH");
            }
        }
    }
}
```

```toml
[package]
name = "app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
version = "0.54.0"
features = [
    "implement",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_Media_Audio",
    "Win32_Media_Multimedia",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_Media_KernelStreaming",
    "Win32_System_Variant",
]

[dependencies.windows-core]
version = "0.54.0"
```

Seems to work as intended here, but I didn't write it out to disk or play it back to verify.

Pay careful attention to the loop commentary here: https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/ApplicationLoopback/cpp/LoopbackCapture.cpp#L361

**Comment by riverar** [comment] 2024-04-15 23:23
Closing this as there's no windows crate bug here to track, but please feel free to respond/continue the discussion.

**Closed by riverar** 2024-04-15 23:23 UTC
Labels: question

**Comment by riverar** [comment] 2024-04-15 23:28
Also beware the capture client will not provide frames in this sample if the process isn't rendering audio (e.g., volume 0). So keying off `GetNextPacketSize` returning 0 is probably not a keen strategy if you have no control over the user/renderer.

**Comment by JohnMitchell04** [comment] 2024-04-16 17:15
Hi @riverar thanks for the help. It appears I probably didn't test the previous code enough as both it and your code does work, just not with the specific process I was using, guess I have some more work to do.
