### ISSUE TITLE
Bug: Access violation related to xinput when closing the window

### ISSUE THREAD

**Issue by CodeUno** [microsoft/windows-rs#1536] opened 2022-02-14 20:57 UTC
### Which crate is this about?

windows-sys

### Crate version

0.32.0

### Summary

Using xinput to get input from xbox controller works correctly but the application cannot close properly.
Application terminates with an access violation whenever I use the XInputGetState function.
I close the window with the top right x button.

The bug is easy to reproduce as seen in this example.

```rust
use windows_sys::{
    Win32::UI::Input::XboxController::*, Win32::Foundation::*, Win32::Graphics::Gdi::ValidateRect,
    Win32::System::LibraryLoader::GetModuleHandleA, Win32::UI::WindowsAndMessaging::*,
};

fn main() {
    unsafe {
        let instance = GetModuleHandleA(std::ptr::null_mut());
        debug_assert!(instance != 0);

        let window_class = b"window\0".as_ptr();

        let wc = WNDCLASSA {
            hCursor: LoadCursorW(0, IDC_ARROW),
            hInstance: instance,
            lpszClassName: window_class,
            style: CS_HREDRAW | CS_VREDRAW,
            lpfnWndProc: Some(wndproc),
            cbClsExtra: 0,
            cbWndExtra: 0,
            hIcon: 0,
            hbrBackground: 0,
            lpszMenuName: std::ptr::null_mut(),
        };

        let atom = RegisterClassA(&wc);
        debug_assert!(atom != 0);

        CreateWindowExA(
            0,
            window_class,
            b"This is a sample window\0".as_ptr(),
            WS_OVERLAPPEDWINDOW | WS_VISIBLE,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            0,
            0,
            instance,
            std::ptr::null_mut(),
        );

        let mut message = std::mem::zeroed();

        while PeekMessageA(&mut message, 0, 0, 0, PM_REMOVE) != 0 {
            DispatchMessageA(&message);
        }
        
        let mut controller_state: XINPUT_STATE = std::mem::zeroed();
        if XInputGetState(0, &mut controller_state) == ERROR_SUCCESS {
            let gamepad: &XINPUT_GAMEPAD = &controller_state.Gamepad;
        }
    }
}

extern "system" fn wndproc(window: HWND, message: u32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    unsafe {
        match message as u32 {
            WM_PAINT => {
                println!("WM_PAINT");
                ValidateRect(window, std::ptr::null());
                0
            }
            WM_DESTROY => {
                println!("WM_DESTROY");
                PostQuitMessage(0);
                0
            }
            _ => DefWindowProcA(window, message, wparam, lparam),
        }
    }
}

```

### Expected behavior

The application should close properly.

### Actual behavior

Application terminates with an access violation.

### Additional comments

A very similar problem seems to be described in this thread:
https://docs.microsoft.com/en-us/answers/questions/516621/access-violation-in-xinputuapdll-when-closing-the.html

**Comment by riverar** [comment] 2022-02-14 21:53
Hey @CodeUno this appears to be a dupe of #824 so going to close this one.

I do see the AV (after tweaking the repro to keep the window open):
```
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFCC929900C: (caller: 00007FFCC929C6AA) ReturnHr(1) tid(6974) 80070005 Access is denied.
```

**Closed by riverar** 2022-02-14 21:53 UTC
Labels: question
