### ISSUE TITLE
Bug: COM Initialize() and Set*() should use `&mut self`

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#1655] opened 2022-04-03 15:50 UTC
### Which crate is this about?

windows

### Crate version

0.34.0

### Summary

Those are expected to be setters, so it's natural that they should use `&mut self`.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Kagami\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.59.0 (9d1b2106e 2022-02-23)

### Reproducible example

```rust
#[implement(Windows::Win32::Graphics::Imaging::IWICBitmapDecoder)]
#[derive(Default)]
pub struct Foo {
    decoded: Option<Rc<RefCell<DecodeProgress>>>,
}

impl IWICBitmapDecoder_Impl for Foo {
    fn Initialize(
        &self, // no mutability, can't initialize without RefCell hack
        pistream: &Option<IStream>,
        _cacheoptions: WICDecodeOptions,
    ) -> windows::core::Result<()> {}
}
```

### Crate manifest

```toml
[dependencies.windows]
version = "0.34.0"
features = [
  "alloc",
  "implement",
  "Win32_Graphics_Imaging",
  "Win32_Foundation",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemServices",
  "Win32_UI_Shell",
  "Win32_UI_Shell_PropertiesSystem",
]
```

### Expected behavior

&mut self

### Actual behavior

&self

### Additional comments

Regressed by https://github.com/microsoft/windows-rs/pull/1511

**Comment by kennykerr** [comment] 2022-04-03 22:39
#1511 was not a regression but a fix for #1497 where I was reliably informed by our C++ and Rust compiler engineering teams that `&mut self` leads to unsound code generation, regardless of whether the method is logically mutable. I [added this test](https://github.com/microsoft/windows-rs/blob/master/crates/tests/nightly_vector/tests/test.rs) in part to illustrate one way that COM-based mutability can be implemented correctly in Rust.

**Comment by saschanaz** [comment] 2022-04-03 23:52
I don't think using `&self` is sound for mutating methods. The fact that the change fixed some things doesn't automatically make this non-regression.

**Comment by kennykerr** [comment] 2022-04-04 01:07
The compiler team was pretty clear that &mut self cannot possibly be sound due to the aliasing rules the compiler depends on. @rylev may have more info to share.

**Comment by kennykerr** [comment] 2022-04-04 22:45
`this: *mut Self` isn't practical because the generator doesn't know which methods should be logically mutable ahead of time. There's no metadata for that. Even if there were, COM methods that are logically read-only might also want to have an internal mutable implementation. That's why I just settled on `&self` and an implementation can rely on something like `RwLock` to safely and correctly mutate. This also encourages thread-safety by default.

**Comment by saschanaz** [comment] 2022-04-04 23:52
>the generator doesn't know which methods should be logically mutable ahead of time.

That's why I set the title like that 🤔

> Even if there were, COM methods that are logically read-only might also want to have an internal mutable implementation.

Sure.

> That's why I just settled on `&self` and an implementation can rely on something like `RwLock` to safely and correctly mutate. This also encourages thread-safety by default.

That means forcing `&self` is to advertise thread-safe solutions. I guess that's what linters should do. 

About soundness issue, wouldn't setting everything as non-mutable disable Rust's borrow checks and make things fragile?

**Comment by kennykerr** [comment] 2022-04-05 03:10
To be clear, this isn't very intuitive to me either even if makes sense to the compiler devs. 😉 

I'll keep noodling on this and hopefully find ways to improve the overall experience. Thanks for the feedback! Definitely something that we should [add to an FAQ](https://github.com/microsoft/windows-rs/issues/1647). 😄

**Comment by kennykerr** [comment] 2022-04-05 03:16
Here's the start of an explanation that I'm working on... The fundamental issues is that ​`&mut self`​ tells the Rust compiler that you as the implementer have exclusive access to the object. Because of this guarantee, the aliasing rules are such that the Rust compiler will make all kinds of guarantees and optimizations about data access that are simply not true if you have a COM interface pointer behind the scenes calling into that implementation. `​&self`​ on the other hand is Rust's way of saying that multiple readers may have simultaneous access but its fine because there is no mutable reference at that point so nobody can possibly trample on anyone else. This is perfectly compatible with COM for obvious reasons. So then if you need mutable access you need to do something explicit that is both compatible with COM and explicitly tells the Rust compiler that this is what is going on. Enter `​RwLock`​​.

**Comment by saschanaz** [comment] 2022-04-05 16:22
I mean, what if:

```rs
// pseudo code...
let mut foo: IFoo = Foo::new().into();
let bar: &[u16] = foo.to_impl().bar(); // borrowing the internal thing...

foo.Initialize(); // this originally had to borrow mutable self so was a compiler error, but not anymore. Boom?
```

**Comment by kennykerr** [comment] 2022-04-05 18:26
`ToImpl` is a separate but related issue that still needs some work. #1615

@rpjohnst may have additional comments - he originally made me aware of the compiler issues.

**Comment by rpjohnst** [comment] 2022-04-05 21:24
These methods cannot use `&mut self` for the same reason that Rust's standard `Rc` and `Arc` types cannot implement `DerefMut`: COM objects must always account for the possibility of multiple references, because they all expose `AddRef` and `QueryInterface` which allow the construction of those additional references.

Specifically, there are two fundamental language rules that everything else here is built on top of:
* `&mut T` is exclusive, so while it is live all access (including taking new references) to the `T` must go through it, or references/pointers derived from it.
* `&T` is immutable for parts of `T` not wrapped in an `UnsafeCell`, so while it is live all access must be read-only (and taking a `&mut` does not count as read-only).

Both user/library code and the compiler assume these rules are never violated. If they are, you may get memory corruption and/or miscompilation depending on how things interact. (It is not always obvious why this a problem at the user level- after all a single thread writing to an `i32` doesn't make a corresponding `&i32` dangling or anything. But the rules were chosen to be "overly strict" like this partially to make them 100% foolproof and compiler-checkable for safe code, partially to make them simpler to follow, and partially to enable compiler optimizations, so we must follow them even in cases like this that "seem okay.")

This is already enough to explain why taking `&mut self` is incorrect: if you have multiple `IFoo`s to the same object floating around (remember `AddRef` and `QueryInterface` are always available), forming a `&mut self` reference from one conflicts with whatever is going on with the others.

saschanaz's example is also broken according to these rules: there is a `&[u16]` into the object, and it is mutated while that reference is live. Using `&mut self` is not enough to fix this, though, even if it were an option. Again consider another live `IFoo` pointing to the same object- borrowing a `&[u16]` from it would not prevent calling `Initialize` on the original!

At the end of the day, this means COM is stuck with `&self`, and everything else about the design needs to deal with that. One consequence here is that `ToImpl` can't use `&mut T`- from the discussion there it sounds like it might need to switch to `&T` and/or become `unsafe`. Another consequence is that any references to internals like saschanaz's `&[u16]` must somehow account for potential reentrant/concurrent/parallel access from other sources- e.g. by wrapping it in an `RwLock`, if it may be mutated.

There are a lot of options here that might be worth exploring. The simplest is what windows-rs does today- punt interior mutability to the user by passing `&self` and expect them to use `RwLock`, atomics, `UnsafeCell`, etc. when they need mutation. Rust's `Rc` and `Arc` types offer a `get_mut` API that conditionally provides a `&mut T` when the refcount is 1, which might make sense for some interfaces. COM also has the concept of a "single threaded apartment" that guarantees all method calls on an object will run on the same thread, which could enable support for single-threaded `RefCell`/`Cell`. Overall I would just emphasize that these are not so much "hacks" as they are *the only way* to do shared mutable objects in Rust.

**Comment by saschanaz** [comment] 2022-04-06 00:00
Thank you for the details, this makes sense then! The suggested `get_mut`-like option would still be cool 👍

**Comment by rylev** [comment] 2022-04-07 08:14
I believe the only things to do here is address https://github.com/microsoft/windows-rs/issues/1615 and perhaps adapt some of @rpjohnst's explanation for documentation about how windows-rs COM works. Going to close this then since those issues are being tracked elsewhere. Let me know if I should reopen this or open another issue to track additional work.

**Closed by rylev** 2022-04-07 08:14 UTC
Labels: question
