### ISSUE TITLE
IStorage functions have wrong signature

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/windows-rs#1854] opened 2022-06-23 00:05 UTC
`StgOpenStorage` and `IStorage::OpenStorage` both have arguments of type `IStorage*` (parameter pstgPriority) but their generated functions have arguments of type `IntoParam<'a, IStorage>` which means we are not able to provide ie. a null to these functions, even through the docs for this function say "A pointer to the IStorage interface that should be NULL. If not NULL, this parameter is used as described below in the Remarks section."

Furthermore, both of these functions return an `IStorage*` type through their out pointer yet the generated rust functions return `Result<IStorage>`

**Comment by riverar** [comment] 2022-06-27 06:08
Transferred to the windows-rs repository, doesn't look like a metadata issue.

**Comment by tim-weis** [comment] 2022-06-27 08:20
It seems that everything is working as designed. It's just that the rules aren't entirely obvious.

The `windows` crate translates COM `[out]` pointers plus `HRESULT` return values into `Result` types for convenient error propagation. (I'm not entirely clear on the specifics of where this transformation is done, but for `StgOpenStorage` this is true.)

The other transformation is (hidden behind) the `IntoParam` trait. It can construct an interface pointer from an `Option`. Passing `None` is equivalent to passing a `nullptr` at the ABI.

The following code compiles and appears to exhibit the desired behavior.

```toml
[dependencies.windows]
version = "0.38.0"
features = [
    "alloc",
    "Win32_System_Com_StructuredStorage",
]
```

```rust
use windows::{
    core::Result,
    Win32::System::Com::StructuredStorage::{
        StgOpenStorage, STGM_READ, STGM_SHARE_EXCLUSIVE, STGM_SIMPLE,
    },
};

fn main() -> Result<()> {
    let _stg = unsafe {
        StgOpenStorage(
            "test.xls",
            None,
            STGM_SIMPLE | STGM_READ | STGM_SHARE_EXCLUSIVE,
            core::ptr::null(),
            0,
        )
    }?;

    Ok(())
}
```

**Comment by rylev** [comment] 2022-06-27 09:27
Thanks for the explanation @tim-weis! 

The reason we don't let `core::ptr::null()` work is that at the type system level, we don't want to allow arbitrary pointers. While passing a null pointer is always safe, passing a non-null pointer might not be safe. Consider the following theoretical very broken code that we don't want to allow:

```rust
let x: usize = 0xdeadbeef;
let ptr = x as *const IStorageVTable;
// passing `ptr to `StgOpenStorage` would obviously be wrong
```

Therefore, we use strongly typed interface types. Interface types in the windows crate are never null. However, `IntoParam` allows you to pass an `Option<IStorage>` which represents the fact that the argument is an optional `IStorage` interface. Thus, `None`, works fine. 

How we're handling params is being changed in #1811, so I think it would be wise to merge that before adding an entry to the FAQ. 

However, even after that PR merges, the answer would be the same: passing `None`. After the PR merges, the type of that parameter will be `P: Into<InParam<'a, IStorage>>` (i.e., any type `P` that can be turned into an `InParam<'a, IStorage>`. `None` will still work here because `Option<&'a IStorage>` implements `Into<InParam<'a, IStorage>>`. However, we might want to consider adding an `InParam::null` method as well. Therefore, anyone who is thinking "I want to pass a null pointer here", will find a solution that maps neatly to their mental mode.

**Closed** 2022-06-30 15:53 UTC
Labels: question
