### ISSUE TITLE
Calling IDXGIAdapter::GetDesc causes crash upon exiting the parent function

### ISSUE THREAD

**Issue by jbuschdev** [microsoft/windows-rs#574] opened 2021-03-05 22:18 UTC
```rust
use bindings::{
    windows::*,
    windows::win32::dxgi::*,
};

fn create_factory() -> Result<IDXGIFactory1> {
    unsafe {
        let mut factory: Option<IDXGIFactory1> = None;
        CreateDXGIFactory1(&IDXGIFactory1::IID, factory.set_abi()).and_some(factory)
    }
}

fn print_adapter_luids() -> Result<()> {
    let factory = create_factory()?;

    let mut adapter_index: u32 = 0;
    loop {
        let mut adapter : Option<IDXGIAdapter1> = None;
        if unsafe { factory.EnumAdapters1(adapter_index, &mut adapter).is_ok() } {
            let adapter = adapter.unwrap();
            let mut desc: DXGI_ADAPTER_DESC = Default::default();
            if unsafe { adapter.GetDesc(&mut desc).is_ok() } {
                println!("adapter luid: {:?}", desc.adapter_luid);
            }
            adapter_index += 1;
        } else {
            break;
        }
    }

    Ok(())
} // crashes here

fn main() -> Result<()> {
    println!("before");
    print_adapter_luids()?;
    println!("after"); // never reaches here
    Ok(())
}

/// active toolchain:
// stable-x86_64-pc-windows-msvc (default)
// rustc 1.50.0 (cb75ad5db 2021-02-10)
/// bindings/Cargo.toml: 
// windows = "0.3.1"
```

The title sounds odd, but I wanted to be precise... I tried forcing destructors w/ explicit `drop` or using simple scopes to make sure the variables were destructed earlier, but nothing could trigger the crash earlier. It still only happens when the function is returning. The debugger makes it look like `RBP` is 0x0 after stepping through a bunch of `drop_in_place` calls, which implies something trashed the stack in that process. 

Here's a min-repro which will never print `"after"` because it crashes when returning from `print_adapter_luids`.

This probably happens with other APIs, as it seems to be happening outside of this code. I haven't narrowed it down much further, but if I don't call `GetDesc`, then the function returns clean (so `CreateDXGIFactory1` and `EnumAdapters` are okay to call). If I do call `GetDesc`, the code in the loop works correctly (It will print out 3 adapter LUIDs for my machine), but then I get a nullptr exception **after** returning from `print_adapter_luids`. 

Is there something I'm missing or using incorrectly?

**Comment by jbuschdev** [comment] 2021-03-06 18:42
Oddly enough turning optimizations to full gave a better debugging experience and even a sensible call-stack...

`config.toml` used for debugging now

```toml
[profile.dev]
opt-level = 3
debug = 2
```

The crash seems to be when this var gets dropped ` let adapter = adapter.unwrap();` Originally `opt-level = 0` when I first wrote the issue which made it appear to crash when returning from the function. w/ `opt-level = 3` it crashes when `adapter` is dropped, which makes way more sense. (UB -> 🎉)

This shows the crash is in `impl Drop for IUnknown` -> `self->__0.**pointer** was nullptr.`  which seems more like we're calling Release() on a nullptr. So now the question is, how did that happen with this code snippet? 

It's still specifically the call to `GetDesc` that ultimately results in the crash when dropping `adapter`. So did that call to `GetDesc` create a new ComPtr but not increment the ref count?

**Comment by jbuschdev** [comment] 2021-03-06 18:55
`opt-level = 1` was sufficient to get a better call stack. 

It's actually any usage of `adapter` after that first call to `GetDesc` which will crash, because the underlying IUnknown is nullptr at that point.

```rust
let adapter : IDXGIAdapter1 = adapter.unwrap();
let mut desc: DXGI_ADAPTER_DESC = Default::default();
println!("adapter before GetDesc: {:?}", adapter);
if unsafe { adapter.GetDesc(&mut desc).is_ok() } {
    println!("adapter luid: {:?}", desc.adapter_luid);
}
println!("adapter after GetDesc: {:?}", adapter);
```
outputs:
```
adapter before GetDesc: 0x1f68f82b960
adapter luid: LUID { low_part: 105, high_part: 0 }
adapter after GetDesc: 0x0
```

Any thoughts?

**Comment by kennykerr** [comment] 2021-03-06 20:16
I'll take a look when I get back to my desk. Thanks for the repro!

**Comment by kennykerr** [comment] 2021-03-08 14:06
The `DXGI_ADAPTER_DESC1` struct has an array member that is isn't yet handled properly by code gen. That throws off the size of the struct. I should be able to fix this soon.

**Comment by DefaultRyan** [comment] 2021-03-08 18:46
Just to provide another data point, this thread title jogged my memory, and I can confirm I had the exact same problem in the C++ projection, and it was also being caused by the same "size-of-struct-due-to-array-member" problem.

**Comment by kennykerr** [comment] 2021-03-16 21:19
This is fixed as of https://github.com/microsoft/windows-rs/pull/608

**Closed** 2021-03-16 21:47 UTC
Labels: bug
