### ISSUE TITLE
Unable to make a default ID3DInclude

### ISSUE THREAD

**Issue by TheElixZammuto** [microsoft/windows-rs#1668] opened 2022-04-07 19:44 UTC
Hi,
I'm trying to use the `D3DCompileFromFile` function for compiling an HLSL shader (https://docs.microsoft.com/en-us/windows/win32/api/d3dcompiler/nf-d3dcompiler-d3dcompilefromfile):

`
windows::Win32::Graphics::Direct3D::Fxc::D3DCompileFromFile(
            "file.hlsl",
            std::ptr::null(),
            std::ptr::null(),
            "main_ps",
            "ps_5_0",
            D3DCOMPILE_ENABLE_STRICTNESS,
            0,
            code,
            error_msg
        );
`

this casues the error `error[E0277]: the trait bound *const _: IntoParam<'_, windows::Win32::Graphics::Direct3D::ID3DInclude> is not satisfied`

It also seems that I cannot find any instance of D3D_COMPILE_STANDARD_FILE_INCLUDE or similar ways to pass the default behavior as a parameter. Is there any workaround to fix this? I cannot find any hint while looking at the documentation.

Thank you in advance!

**Comment by kennykerr** [comment] 2022-04-07 19:54
Hey! I have no idea how this API is meant to work but you should be able to call it as follows.

```
[dependencies.windows]
version = "0.35"
features = [
    "alloc",
    "Win32_Graphics_Direct3D_Fxc",
]
```

```rust
use windows::{core::*, Win32::Graphics::Direct3D::Fxc::*};

fn main() -> Result<()> {
    unsafe {
        let mut code = None;
        let mut message = None;
        D3DCompileFromFile(
            "file name",
            std::ptr::null(),
            None,
            "entry point",
            "target",
            0,
            1,
            &mut code,
            &mut message,
        )
    }
}
```

I see that [D3D_COMPILE_STANDARD_FILE_INCLUDE](https://docs.microsoft.com/en-us/windows/win32/api/d3dcompiler/nf-d3dcompiler-d3dcompilefromfile) is pretty wacky. I'll have to think about that.

**Comment by TheElixZammuto** [comment] 2022-04-07 20:27
Seems that passing "None" as the parameter did the trick, thank you!

**Comment by rylev** [comment] 2022-04-08 12:27
🎉 We have issues open for documenting more clearly how to make types line up properly, so I'm going to close this.

**Closed by rylev** 2022-04-08 12:27 UTC
Labels: question

**Comment by jmracek** [comment] 2024-01-24 20:39
Want to follow up here, since it's been nearly two years since this issue was closed and yet I still had exactly the same confusion. 
 I only stumbled into this closed issue by using Github search for `IntoParam<ID3DInclude>`, which happened to have this thread as the sole result.

The problem is clear: The documentation lists `pinclude` as an object whose type implements `IntoParam<ID3DInclude>`, but it is not at all clear from the local context of the documentation that `IntoParam<T>` [has a blanket impl](https://github.com/microsoft/windows-rs/blob/master/crates/libs/core/src/param.rs#L42) for `Option<&T>` that I assume is handling this case.

It feels like I could have avoided this confusion if the `IntoParam` trait didn't have it's [documentation hidden](https://github.com/microsoft/windows-rs/blob/master/crates/libs/core/src/param.rs#L27), and the doc page for that trait had a section explicitly calling out the use case of default parameters.
