### ISSUE TITLE
Can't find `Lines` method for OcrResult

### ISSUE THREAD

**Issue by PrivateRookie** [microsoft/windows-rs#856] opened 2021-06-11 08:00 UTC
When calling `Lines` for OcrResult struct according to [Doc](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Media/Ocr/struct.OcrResult.html), I got compile error

```pwsh
error[E0599]: no method named `Lines` found for struct `OcrResult` in the current scope
  --> src\main.rs:71:28
   |
71 |         for line in result.Lines().unwrap() {
   |                            ^^^^^ method not found in `OcrResult`
```

codes are the same as [ocr example](https://github.com/microsoft/windows-rs/blob/master/examples/ocr/src/main.rs), except for calling `Lines` method.

crate version: 0.11 or 0.10
rust version: stable-x86_64-pc-windows-msvc 1.52.1
os version: Microsoft Windows NT 10.0.19043.0

**Comment by tim-weis** [comment] 2021-06-11 11:12
Sounds like a duplicate of #594. If it isn't, could you provide a repro?

**Closed** 2021-06-11 15:07 UTC

**Comment by kennykerr** [comment] 2021-06-23 16:31
As of 0.12.0 (#896), methods are no longer omitted so this should no longer be an issue.
