### ISSUE TITLE
Shell_NotifyIconW fails with 0x80004005 since windows-rs 0.11

### ISSUE THREAD

**Issue by mlehmannm** [microsoft/windows-rs#912] opened 2021-06-25 12:24 UTC
Since windows-rs 0.11 a call to Shell_NotifyIconW to add an icon to the tray fails with 0x80004005.

Maybe the attribute change on NOTIFYICONDATAA / NOTIFYICONDATAW from

#[repr(C)]

to

#[repr(C, packed(1))]

causes this issue?

**Comment by kennykerr** [comment] 2021-06-25 18:04
The Windows crate doesn't yet distinguish between different target architectures when it comes to generating API definitions that differ from architecture to architecture. The [win32 metadata](https://github.com/microsoft/win32metadata) did however recently introduce architecture-specific definitions for those APIs that differ. This may be causing the issue you're seeing here.

**Comment by kennykerr** [comment] 2021-06-25 18:08
Duplicate of #858

**Closed by kennykerr** 2021-06-25 18:08 UTC
