### ISSUE TITLE
Feature request: convenience macros/functions

### ISSUE THREAD

**Issue by Razordor** [microsoft/windows-rs#1984] opened 2022-08-25 01:29 UTC
### Motivation

certain macros such as [MAKEINTRESOURCE](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-makeintresourcea), and [GET_X_LPARAM](https://docs.microsoft.com/en-us/windows/win32/api/windowsx/nf-windowsx-get_x_lparam) aren't in windows-rs which would make using functions like [LoadImage](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-loadimagea) inconvenient. Adding convenience macros would make useability easier.

### Drawbacks

Drawback could be further bloating the crate

### Rationale and alternatives

convenience macros could be const functions, or declarative macros.

**Comment by riverar** [comment] 2022-08-25 04:46
Duplicate of #641

**Comment by ryancerium** [comment] 2022-08-25 05:23
...and #921 and #1205 and #1445...

I'm beginning to think we should do something about this.  Maybe make a `windows-rsEx` crate? 😆

**Comment by kennykerr** [comment] 2022-08-25 13:31
Yep, a dedicated crate for macros seems appropriate.

**Closed** 2022-08-25 15:06 UTC
Labels: question
