### ISSUE TITLE
Missing `WTS_CURRENT_SERVER_HANDLE`?

### ISSUE THREAD

**Issue by dilawar** [microsoft/windows-rs#2316] opened 2023-01-29 05:21 UTC
I can't find `WTS_CURRENT_SERVER_HANDLE`. It is used in various APIs such as https://learn.microsoft.com/en-us/windows/win32/api/wtsapi32/nf-wtsapi32-wtsquerysessioninformationa?redirectedfrom=MSDN. 

Is it missing? If not, what is the recommended alternative? Can I pass `0` or `None` in https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/RemoteDesktop/fn.WTSQuerySessionInformationW.html?

**Comment by riverar** [comment] 2023-01-29 05:24
Dupe of https://github.com/microsoft/win32metadata/issues/1403, it should get fixed soon. `HANDLE::default()` or `HANDLE(0)` should do.

**Closed** 2023-01-29 06:07 UTC
Labels: question
