### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by Cupnfish** [microsoft/windows-rs#620] opened 2021-03-19 02:09 UTC
I found `bindings::windows::win32::menus_and_resources::DestroyAcceleratorTable` in a [document search](https://microsoft.github.io/windows-docs-rs/doc/bindings/index.html?search=DestroyAcceleratorTable), but it’s actually this: `bindings::windows::win32::windows_and_messaging::DestroyAcceleratorTable`. 
Is this a recent change?

**Comment by tim-weis** [comment] 2021-03-19 08:21
I noticed that types in the generated [Win32Metadata](https://github.com/microsoft/win32metadata) started moving around and getting renamed recently (#618). Since there is currently [no up-to-date documentation available](https://github.com/microsoft/windows-rs/issues/614) I downloaded the NuGet package referenced by this crate and opened it in Visual Studio's [Object Browser](https://docs.microsoft.com/en-us/visualstudio/ide/viewing-the-structure-of-code#BKMK_ObjectBrowser) to derive the path names in the Rust bindings. The version of the NuGet package used by *windows-rs* is [documented here](https://github.com/microsoft/windows-rs/tree/master/crates/gen/default).

**Comment by kennykerr** [comment] 2021-03-19 13:33
Duplicate of #614

**Closed by kennykerr** 2021-03-19 13:33 UTC
